### PR TITLE
cnao: make multus-dynamic-networks lane mandatory

### PR DESCRIPTION
**Pull request by maiqueb**
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
/lgtm
/approve
/hold

Hold until https://github.com/kubevirt/cluster-network-addons-operator/pull/1442 is merged

**Comment by maiqueb** [comment]
/hold cancel

kubevirt/cluster-network-addons-operator#1442 was merged.

**Pull request merged**
