### PR TITLE
Remove loki service as no longer required

### PR DESCRIPTION
**Pull request by brianmcarey**
Since the clusters have been moved to OCP - Loki is no longer required as pod logs can be queried through the OCP console.

/cc @dhiller @xpivarc

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by brianmcarey** [comment]
@dhiller - should I apply the following https://github.com/kubevirt/project-infra/pull/3136/commits/0624b38a81b0870ee10fc1bc63b7da9f32d0a1c9 here?

**Comment by dhiller** [comment]
> @dhiller - should I apply the following [0624b38](https://github.com/kubevirt/project-infra/commit/0624b38a81b0870ee10fc1bc63b7da9f32d0a1c9) here?

Hm, must have been something that was introduced by the go bump. Not sure why. Thanks for fixing this

**Pull request merged**
