### PR TITLE
kubevirtci, vgpu: Update lane name

### PR DESCRIPTION
**Pull request by oshoval**
Depends on https://github.com/kubevirt/kubevirtci/pull/979
Should be merged with it.

### CODE REVIEW

**Comment by oshoval** [comment]
/hold

depends on https://github.com/kubevirt/kubevirtci/pull/979

**Comment by oshoval** [comment]
Thanks

**Comment by oshoval** [comment]
@brianmcarey 
can you please run this PR with https://github.com/kubevirt/kubevirtci/pull/979 on top of 979 ?
or you prefer that i will do it manually ?

**Comment by brianmcarey** [comment]
> @brianmcarey can you please run this PR with [kubevirt/kubevirtci#979](https://github.com/kubevirt/kubevirtci/pull/979) on top of 979 ? or you prefer that i will do it manually ?

Yes sure - I can run it.

**Comment by oshoval** [comment]
> > @brianmcarey can you please run this PR with [kubevirt/kubevirtci#979](https://github.com/kubevirt/kubevirtci/pull/979) on top of 979 ? or you prefer that i will do it manually ?
> 
> Yes sure - I can run it.
> 
> Here is the link to the job - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/979/check-up-kind-1.25-vgpu/1633761343699947520

Thanks, passed

**Pull request merged**
