### PR TITLE
Rebuild golang image if bootstrap changes

### PR DESCRIPTION
**Pull request by rmohr**
Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by fgimenez** [comment]
Good catch! But are we tagging bootstrap with `latest`? Not sure if the golang image is going to pick the right one as base https://github.com/kubevirt/project-infra/blob/main/images/golang/Dockerfile#L1

**Comment by rmohr** [comment]
> Good catch! But are we tagging bootstrap with `latest`? Not sure if the golang image is going to pick the right one as base https://github.com/kubevirt/project-infra/blob/main/images/golang/Dockerfile#L1

Hm, that does obviously not work. Right. :/

I  think I never intended treating them in separate jobs. I will just combine them. It will rebuild bootstrap then also when only golang is changed, but I think that is still good enough.

**Comment by rmohr** [comment]
@fgimenez PTAL.

**Comment by fgimenez** [comment]
I think we still need to tag bootstrap with `latest` at least locally (no need to push it) before building the golang image, if not it is not going to be available, wdyt?

**Comment by rmohr** [comment]
> I think we still need to tag bootstrap with `latest` at least locally (no need to push it) before building the golang image, if not it is not going to be available, wdyt?

It is tagged with `bootstrap` already in addition with its `quay.io` name: https://github.com/kubevirt/project-infra/blob/main/images/publish_image.sh#L68. I think that should be sufficient.

**Review by fgimenez — APPROVED** [review]
/approve

**Pull request merged**
