### PR TITLE
Update kubevirt-velero-plugin jobs to use new podman bootstrap

### PR DESCRIPTION
**Pull request by brianmcarey**
/cc @brybacki @maya-r 
Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Comment by brianmcarey** [comment]
@brybacki @maya-r `pull-kvp-unit-test` runs successfully with the new bootstrap when the following is removed:
https://github.com/kubevirt/kubevirt-velero-plugin/blob/70d0b09fdb5291a902ee38fbb631993121497de7/Makefile#L113

`--userns=keep-id` doesn't seem to work with rootful podman, can it be removed or is it required?

**Comment by maya-r** [comment]
Proposed a change for it -- I hope it will do the trick.

**Comment by brianmcarey** [comment]
Thanks @maya-r @brybacki ! I will retry the rehearsals now.

**Comment by brianmcarey** [comment]
Rehearsal runs look good.

**Comment by brybacki** [comment]
besides the typo in the title `s/kubevirt-valero-plugin/kubevirt-velero-plugin/` all is good
/lgtm

**Comment by brianmcarey** [comment]
/cc @dhiller @xpivarc 

Rehearsals were successful for this change

**Pull request merged**
