### PR TITLE
Add dkeler to kubevirt members

### PR DESCRIPTION
**Pull request by dkeler**
Add dkeler to kubevirt members

### CODE REVIEW

**Comment by dkeler** [comment]
# GitHub Username
e.g. (at)example_user

## Requirements

[X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[ ] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[ ] I am actively contributing to KubeVirt<br>
[ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[X] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[X] I have publicly introduced myself to the community through one of the community communication channels<br>

(https://github.com/kubevirt/community#socializing)

## Sponsors

* @avlitman

## List of contributions to the KubeVirt project

* PRs reviewed and/or authored
-

* Issues responded to
-

> [!IMPORTANT]
> After this pull request has been merged, an invitation to the KubeVirt GitHub organization will be automatically sent to the new member. The new member needs to accept the invitation to receive member status.

**Comment by avlitman** [comment]
/cc 
@dhiller

**Comment by avlitman** [comment]
cc @brianmcarey @dhiller can we reopen this and merge?

**Comment by dhiller** [comment]
> cc @brianmcarey @dhiller can we reopen this and merge?

@avlitman please see the membership policy: https://github.com/kubevirt/community/blob/main/membership_policy.md#member

**Pull request closed without merging**
