### PR TITLE
Update nonroot vgpu lane to 1.23

### PR DESCRIPTION
**Pull request by xpivarc**
We don't support 1.19 anymore with the main branch.

### CODE REVIEW

**Comment by xpivarc** [comment]
@rmohr Can you have a look, please?

**Review by jean-edouard — COMMENTED** [review]
This PR both upgrades the lane and makes it gating.
How do we know the upgraded lane will be reliable? If it's not, it will block all PRs...
Would it make sense to upgrade + run always, but wait a few days before switching to required?

**Comment by xpivarc** [comment]
> This PR both upgrades the lane and makes it gating. How do we know the upgraded lane will be reliable? If it's not, it will block all PRs... Would it make sense to upgrade + run always, but wait a few days before switching to required?

Makes sense. I pushed the changes. I think it should be enough to have a few runs as this is almost identical to the existing lane. The difference should cause to fail it almost in all cases if any.

**Review by jean-edouard — APPROVED** [review]
/approve

**Pull request merged**
