### PR TITLE
Sync cri-o version 1.21

### PR DESCRIPTION
**Pull request by rhrazdil**
Adding 1.21 version to be synced with GCP.

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

### CODE REVIEW

**Comment by rhrazdil** [comment]
Noticed that cri-o 1.21 is failing to build in OBS https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.21
That is probably why CentoOS_8_Stream is missing there.

Opened issue on cri-o https://github.com/cri-o/cri-o/issues/4768

**Comment by rhrazdil** [comment]
Issues with cri-o 1.21 build for CentOS_8_Stream was fixed, we can add 1.21 to the list of sync versions.

**Comment by rhrazdil** [comment]
cc @dhiller @fgimenez

**Comment by rmohr** [comment]
/lgtm
/approve

/hold

@rhrazdil feel free to unhold if this is still working properly.

**Comment by rhrazdil** [comment]
Re-tested locally that all is good. Thanks

/hold cancel

**Pull request merged**
