### PR TITLE
[WIP] Monitoring

### PR DESCRIPTION
**Pull request by rmohr**
Add the following things:
 - [x] Prometheus
 - [x] Prometheus Pushgateway
 - [x] Grafana
 - [x] Automatically add Prometheus as Grafana data source
 - [ ] Alertmanager
 - [x] Node Exporter to monitor CI slaves with prometheus
 - [x] Collect node exporter metrics with Prometheus
 - [x] Monitor Prow with the prometheus instance
 - [ ] Automatically add a reasonable dashboard to grafana
 - [ ] configure disk space alerts for alertmanager
 - [x] Secure with tls in combination with basic auth
 - [ ] Grafana config contains "secret" values. Either make it a secret or split it somehow.

### CODE REVIEW

**Comment by rmohr** [comment]
@slintes @cynepco3hahue FYI

**Comment by slintes** [comment]
nice! lgtm

**Comment by slintes** [comment]
/reopen
/remove-lifecycle rotten

see https://github.com/kubevirt/project-infra/pull/64#issuecomment-446225692

**Comment by rmohr** [comment]
/close

Will be superseeded with a prow-focused solution.

**Pull request closed without merging**
