### PR TITLE
k8s-1.24-ipv6: Add provision lane

### PR DESCRIPTION
**Pull request by oshoval**
Add k8s-1.24-ipv6 lane

Depends on https://github.com/kubevirt/kubevirtci/pull/808

### CODE REVIEW

**Comment by oshoval** [comment]
Cnao deployment stuck, according Brian lets try with crio 1.22

**Comment by oshoval** [comment]
@brianmcarey 
with CRI-O 1.22 it passes, thanks for the tip, once we are conclude about CRI-O version
and https://github.com/kubevirt/kubevirtci/pull/808 we can clean this one and review it please.

**Comment by brianmcarey** [comment]
@oshoval  - it looks like we are hitting the same issue with the standard 1.24 provider. I think I will update the 1.24 provider to use cri-o 1.22 until https://github.com/cri-o/cri-o/issues/5889 is resolved as it could cause intermittent issues.

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2145/rehearsal-check-provision-k8s-1.24-ipv6/1534469276952432640

passed, removing the debug commit

**Comment by oshoval** [comment]
@brianmcarey 
can you please take a look ?

**Comment by oshoval** [comment]
> Just a quick quesion - will an ipv6 singlestack lane be required for each k8s version going forward? Or do we require to test this against just one version of kubernetes?
> 
> As in should we remove check-provision-k8s-1.22-ipv6 once this lane is running regularly?

We will be able to remove 1.22-ipv6 once 1.24-ipv6 is operational
Thanks

**Pull request merged**
