### PR TITLE
Migrate kubevirtci check-provision jobs to new workloads cluster

### PR DESCRIPTION
**Pull request by brianmcarey**
This change also removes some of the presubmit lanes that are no longer needed. 

/cc @dhiller @xpivarc

### CODE REVIEW

**Comment by brianmcarey** [comment]
Passed run of [check-provision-k8s-1.25](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/976/check-provision-k8s-1.25/1640997214224388096) against the new cluster

**Review by dhiller — COMMENTED** [review]
/approve

Thank you @brianmcarey !

/hold to see rehearse results, remove anytime :)

**Review by dhiller — APPROVED** [review]

**Pull request merged**
