### PR TITLE
Move priority/backlog to global label definition

### LINKED ISSUE #3654: Move priority/backlog to global label definition
The label [priority/backlog](https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#priority/backlog) should be moved to the global section `.default.labels` in the label config file [labels.yaml] - adjacent to the label [priority/critical-urgent](https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#priority/critical-urgent)

Editing our GitHub labels is done by editing the [labels.yaml] - similarly to adding a label [2], and running `make update-labels` afterwards, which will update the `labels.md` file.

Please do all this in one commit, so we have the changes grouped together nicely.

See [issue comment](https://github.com/kubevirt/project-infra/issues/3653#issuecomment-2355597608) as example.

[1]: https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#intro
[2]: https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#how-do-i-add-a-new-label
[3]: https://github.com/kubevirt/project-infra/blob/3be67a4d732dc9d02bf6ab2c67dae28088aaeec6/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml#L368
[labels.yaml]: https://github.com/kubevirt/project-infra/tree/main/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

### PR DESCRIPTION
**Pull request by anishbista60**
**What this PR does / why we need it**:
- Move priority/backlog to global label definition adjacent to [priority/critical-urgent](https://file+.vscode-resource.vscode-cdn.net/home/anishbista/project-infra/docs/labels.md#priority/critical-urgent)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3654

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by anishbista60** [comment]
@dhiller Request for review ?

**Comment by dhiller** [comment]
> @dhiller Request for review ?

You mean

/cc @dhiller

**Comment by dhiller** [comment]
@anishbista60 the file you have changed is auto-generated, therefore changing it will have no effect on the label definitions.

Editing our GitHub labels is done by editing the [labels.yaml] - similarly to adding a label [2] - thus we need to move the label definition of `priority/backlog` [3] to somewhere below the yaml path `.default.labels` (best would be to place it adjacent to the other `priority` label.

Afterwards you need to run `make update-labels`, which will update the `labels.md` file.

Please do all this in one commit, so we have the changes grouped together nicely.

Thank you for looking into this!

[1]: https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#intro
[2]: https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#how-do-i-add-a-new-label
[3]: https://github.com/kubevirt/project-infra/blob/3be67a4d732dc9d02bf6ab2c67dae28088aaeec6/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml#L368
[labels.yaml]: https://github.com/kubevirt/project-infra/tree/main/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml

**Comment by dhiller** [comment]
@anishbista60 I have update the issue description also - hope the task is more clear now. Sorry for the confusion.

**Comment by anishbista60** [comment]
@dhiller Thank you

**Comment by anishbista60** [comment]
> @anishbista60 the file you have changed is auto-generated, therefore changing it will have no effect on the label definitions.
> 
> Editing our GitHub labels is done by editing the [labels.yaml](https://github.com/kubevirt/project-infra/tree/main/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml) - similarly to adding a label [2](https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#how-do-i-add-a-new-label) - thus we need to move the label definition of `priority/backlog` [3](https://github.com/kubevirt/project-infra/blob/3be67a4d732dc9d02bf6ab2c67dae28088aaeec6/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml#L368) to somewhere below the yaml path `.default.labels` (best would be to place it adjacent to the other `priority` label.
> 
> Afterwards you need to run `make update-labels`, which will update the `labels.md` file.
> 
> Please do all this in one commit, so we have the changes grouped together nicely.
> 
> Thank you for looking into this!

Thanks for great  explanation, made so easy . 
Now, every thing done. Please check.

**Review by dhiller — APPROVED** [review]
/approve

Thank you!

**Comment by anishbista60** [comment]
@dhiller `pull-project-infra-prow-deploy-test` failing

**Comment by anishbista60** [comment]
@brianmcarey could you please look into ? unable to get the exact reason

**Comment by anishbista60** [comment]
if you don't mind could you  please hold this PR till october 1st ? 
 for `hacktoberfest`.

**Comment by dhiller** [comment]
@anishbista60 no issues with 

/hold

until Oct

**Comment by anishbista60** [comment]
@dhiller please unhold it . Thanks

**Pull request merged**
