### PR TITLE
Update kubevirt.github.io jobs to pull from repo

### PR DESCRIPTION
**Pull request by cwilkers**
Signed-off-by: cwilkers <cwilkers@redhat.com>

We need ruby and other files from the kubevirt.github.io repo during build.

### CODE REVIEW

**Comment by cwilkers** [comment]
/cc @brianmcarey 
It looks like a chicken/egg problem, I can't fix the pre-submit because I can't pass the pre-submit.

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
Since the presubmit is not yet required it doesn't prohibit automatic merging, thus we should be good to go.

As a followup we should make the presubmit required (aka optional: false or remove optional in job spec) once it succeeds.

**Comment by dhiller** [comment]
Strange, tide complained about the job failing, maybe there's some config problem. We need to revisit that.

**Pull request merged**
