### PR TITLE
Rollback to previous bootstrap image

### PR DESCRIPTION
**Pull request by fgimenez**
Aiming to remove the fedora image as a potential source of instability.

/cc @rmohr @dhiller 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
Could we maybe copy the image to quay to not run into the rate limit again?

**Comment by fgimenez** [comment]
> Could we maybe copy the image to quay to not run into the rate limit again?

Makes total sense, but I'm not sure if rolling back the image is the right approach. We see now a lot of failures but nothing seems to point to the fedora image as the cause. I've just converted it to draft, will continue with it if we determine that this is going to help.

**Comment by rmohr** [comment]
@fgimenez I think we can close this one now. We merged 6 PRs today: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-03-08-024h.html until now.

What do you think?

**Comment by fgimenez** [comment]
/close

makes sense :+1:

**Pull request closed without merging**
