### PR TITLE
Increase performance job memory

### PR DESCRIPTION
**Pull request by rthallisey**
Increase kubevirt mem and job memory

fixes: https://github.com/kubevirt/kubevirt/issues/7658

### CODE REVIEW

**Comment by rthallisey** [comment]
cc @dhiller

**Comment by rthallisey** [comment]
cc @lyarwood

**Comment by xpivarc** [comment]
@rthallisey Would you know how much memory is needed for the performance test right now and why it suddenly stopped working?

**Comment by rthallisey** [comment]
@xpivarc I was wondering the same thing.  Something changed on 4/23 either in CI or in KubeVirt.  We're looking into the kubevirt side in sig-scale.  Do you know if anything in CI changed around 4/23?

**Comment by xpivarc** [comment]
> @xpivarc I was wondering the same thing. Something changed on 4/23 either in CI or in KubeVirt. We're looking into the kubevirt side in sig-scale. Do you know if anything in CI changed around 4/23?

Not to my knowledge. 

https://github.com/kubevirt/kubevirt/pull/7264 Introduce 41Mi overhead per vmi. I think it is the root cause when you take into account 41Mi * 100

**Comment by oshoval** [comment]
we might need this change please also on release 0.53 ?
see please
https://github.com/kubevirt/kubevirt/pull/7684#issuecomment-1122471420

**Pull request merged**
