### PR TITLE
kubevirt: Add optional kubernetes 1.31 presubmits & periodics

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

Lanes created by manually running the following:
```
bazel run //robots/cmd/kubevirt copy jobs -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --job-config-path-kubevirt-periodics=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml --github-token-path= --k8s-release-semver 1.31 --dry-run=false
```

The k8s-1.31 provider has been added to the kubevirt repo[1]

[1] https://github.com/kubevirt/kubevirt/pull/12408

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @dhiller @xpivarc 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by brianmcarey** [comment]
@dhiller  - there is 1 test failure on the 1.31-sig-storage lane but apart from that the rest of the lanes look good. 

I think it is worth adding the lanes to get more data - also having a presubmit available will help sig-storage with troubleshooting the test failure. 
WDYT?

cc @awels @akalenyu

**Comment by akalenyu** [comment]
> @dhiller - there is 1 test failure on the 1.31-sig-storage lane but apart from that the rest of the lanes look good.
> 
> I think it is worth adding the lanes to get more data - also having a presubmit available will help sig-storage with troubleshooting the test failure. WDYT?
> 
> cc @awels @akalenyu

Very weird. Don't see where 1.31 would have an integration point with that simple flow. Maybe PVCs are dangling for a long time, since I see 
Can I get 1.31 on kubevirt main today? so I could debug it locally?

**Comment by brianmcarey** [comment]
> > @dhiller - there is 1 test failure on the 1.31-sig-storage lane but apart from that the rest of the lanes look good.
> > I think it is worth adding the lanes to get more data - also having a presubmit available will help sig-storage with troubleshooting the test failure. WDYT?
> > cc @awels @akalenyu
> 
> Very weird. Don't see where 1.31 would have an integration point with that simple flow. Maybe PVCs are dangling for a long time, since I don't see `CloneWithoutSource` events anywhere. Can I get 1.31 on kubevirt main today? so I could debug it locally?

The beta provider is there in kubevirt/kubevirt - `KUBEVIRT_PROVIDER=k8s-1.31`

**Comment by akalenyu** [comment]
> Maybe PVCs are dangling for a long time, since I don't see `CloneWithoutSource` events anywhere.

Yeah the PVC hanging for a few extra seconds was it. I was able to reproduce locally and could fix it with
```
$ git diff
diff --git a/tests/storage/datavolume.go b/tests/storage/datavolume.go
index ab0a8d2cdd..0a585c41dc 100644
--- a/tests/storage/datavolume.go
+++ b/tests/storage/datavolume.go
@@ -955,6 +955,7 @@ var _ = SIGDescribe("DataVolume Integration", func() {
                                }
                                err = virtClient.CoreV1().PersistentVolumeClaims(testsuite.NamespaceTestAlternative).Delete(context.Background(), dataVolume.Name, metav1.DeleteOptions{})
                                Expect(err).ToNot(HaveOccurred())
+                               Eventually(ThisPVCWith(testsuite.NamespaceTestAlternative, dataVolume.Name), 10*time.Second, 1*time.Second).Should(BeGone())
 
                                // We check if the VM is succesfully created
                                By("Creating VM")
```

**Comment by brianmcarey** [comment]
/override rehearsal-pull-kubevirt-e2e-k8s-1.31-sig-storage

thanks for taking a look into it @akalenyu - we are going to go ahead and merge this PR so we can get more results for the k8s-1.31 provider - as this is a beta provider, it may improve when the 1.31 rc become available.

**Pull request merged**
