### PR TITLE
Release configs for kubevirt/kubevirt release branch release-0.52

### PR DESCRIPTION
**Pull request by davidvossel**
adds new release configs

### CODE REVIEW

**Comment by davidvossel** [comment]
related to https://github.com/kubevirt/kubevirt/pull/6382

**Comment by rmohr** [comment]
@davidvossel can you rebase the PR?

**Comment by rmohr** [comment]
@davidvossel we have issues with the automatic fork of the configs. We miss 0.50 and 0.51 job configs.

**Comment by dhiller** [comment]
/hold

Holding the broken PR, will add a link to a new one later and close this one.

**Comment by dhiller** [comment]
/close 

Closing this one in favor of #2035

**Pull request closed without merging**
