### PR TITLE
Prow workloads bootstrap automation

### PR DESCRIPTION
**Pull request by fgimenez**
Adds an ansible role with all the customizations required to setup e2e worker nodes. Also creates a prow job to run the job on tag push.

/cc @dhiller @rmohr

### CODE REVIEW

**Comment by fgimenez** [comment]
/hold

Waiting to be able to run test job.

**Comment by rmohr** [comment]
I guess for the cache nodes we will need an extra role. Looks good on a quick glance. Do we want to separate images and emptyDir space again like we did in the past?

**Comment by fgimenez** [comment]
> Do we want to separate images and emptyDir space again like we did in the past?

Makes sense to me, I'll prepare a separate role for the cache node.

**Review by dhiller — APPROVED** [review]
/approve

**Comment by fgimenez** [comment]
/retest

imagePullBackoff, maybe we need to increase the retries for pods ready

**Pull request merged**
