### PR TITLE
Build img consolidation and streamline

### PR DESCRIPTION
**Pull request by mazzystr**
Build img consolidation and streamline. We now build a single img containing mkdocs, yaspeller, htmlproofer packed in.

### CODE REVIEW

**Comment by mazzystr** [comment]
@dhiller `_config/src` will cause failures until [user-guide/pull/441](https://github.com/kubevirt/user-guide/pull/441) is merged

**Review by dhiller — APPROVED** [review]
/approve

**Comment by mazzystr** [comment]
@dhiller Error is ...
```
 Step 4/6 : COPY ./_config/src/ ./
COPY failed: stat /docker-graph/tmp/docker-builder001830446/_config/src: no such file or directory 
```
I'm still getting it despite [user-guide/pull/441](https://github.com/kubevirt/user-guide/pull/441) being merged and `_config/src` now existing.  Got any suggestions to get through this?

**Pull request merged**
