### PR TITLE
Remove rhcos-slb project

### PR DESCRIPTION
**Pull request by phoracek**
Replaced via https://github.com/RHsyseng/rhcos-slb/pull/31

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
already opened https://github.com/kubevirt/project-infra/pull/1497 :) 
but your's is more correct, so closing mine. 
/lgtm

**Comment by RamLavi** [comment]
/hold
Let's wait for RHsyseng/rhcos-slb#31 to be merged before this get's merged, is that ok @phoracek ?

**Comment by phoracek** [comment]
@RamLavi sounds good, thanks

**Comment by phoracek** [comment]
@fgimenez when you find some time, would you please take a look?

**Review by fgimenez — APPROVED** [review]
/approve

Thanks!

**Pull request merged**
