### PR TITLE
presubmits: pull-kubevirt-build: add timestamps

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
`automation/test.sh` exports `TIMESTAMP=1` to get timestamped output.
However, `pull-kubevirt-build` does not use that script, therefore its output doesn't get timestamped.
This PR fixes that.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brianmcarey** [comment]
/rehearse

Can this be handled in kubevirt itself? I guess it doesn't make sense to have timestamps on local dev builds?

**Comment by jean-edouard** [comment]
> Can this be handled in kubevirt itself? I guess it doesn't make sense to have timestamps on local dev builds?

Yeah that's the idea, having timestamps only on test lanes, like all e2e lanes.
I'm fine moving this to KubeVirt if there's a reliable way to know that the caller is prow. Maybe it does export some variables by default?

**Comment by brianmcarey** [comment]
> > Can this be handled in kubevirt itself? I guess it doesn't make sense to have timestamps on local dev builds?
> 
> Yeah that's the idea, having timestamps only on test lanes, like all e2e lanes. I'm fine moving this to KubeVirt if there's a reliable way to know that the caller is prow. Maybe it does export some variables by default?

I think we could rely on `CI=true` here like we have done for the e2e jobs. It shouldn't get in the way of local dev. 
https://github.com/kubevirt/kubevirt/blob/e1eb25e536852f9cc1e90c5b6c7a261129f07ea9/automation/test.sh#L32

**Comment by jean-edouard** [comment]
@brianmcarey a few jobs do `cp /etc/bazel.bazelrc ./ci.bazelrc && make [...]`. Would it be possible to add `build --noshow_progress` at the end of that file?
That would improve the readability of the logs by getting rid of all the `[XXX / YYY] doing something...`
See https://github.com/kubevirt/kubevirt/pull/12685

**Pull request closed without merging**
