### PR TITLE
Add testgrid config and transfigure jobs

### PR DESCRIPTION
**Pull request by fgimenez**
These changes will allow us to propose, test and review changes to our TestGrid configuration and, once merged, have them automatically proposed by kubevirt-bot to https://github.com/kubernetes/test-infra

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/hold

Do we have a testrun somewhere already?

**Comment by fgimenez** [comment]
> Do we have a testrun somewhere already?

yep https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/847/pull-project-infra-check-testgrid-config/1350069973724172288 but it is failing, on it

**Comment by fgimenez** [comment]
> Do we have a testrun somewhere already?

@rmohr tests passing here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubevirtci/1351440055884845056

I've also taken the opportunity to add a short readme for people wanting to add more dashboards/jobs to testgrid.

**Comment by rmohr** [comment]
> @rmohr tests passing here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/847/rehearsal-pull-project-infra-check-testgrid-config/1351441440160354306

The test says `dry-run skip PR`, I assume you somehow configured the job to be a dry-run just for the test?

**Comment by fgimenez** [comment]
> The test says `dry-run skip PR`, I assume you somehow configured the job to be a dry-run just for the test?

yes, this comes from the transfigure script, it can be used both for testing and for creating the actual PR to test-infra with the testgrid changes. In this case, given that we are calling transfigure with the `testing` command, the PR is not created (relevant code here https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/transfigure/transfigure.sh#L108-L109)

I created the jobs following this example https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/transfigure/example-prowjobs.yaml more details about transfigure here https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/transfigure

**Pull request merged**
