### PR TITLE
DNM/WIP Add skip_if_only_changed regex to skip jobs

### PR DESCRIPTION
**Pull request by lyarwood**
DNM/WIP as there must be a better way to mass edit these jobs, any feedback would be welcome!

I've used yq to add skip_if_only_changed to jobs without run_if_changed set using the following command:
```
$ docker run -i --rm -v $(pwd):/work mikefarah/yq -i '. | with(.presubmits.kubevirt/kubevirt[]; with(select(.run_if_changed == null); .skip_if_only_changed = "^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$"))' /work/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
```

This appears to give the desired result but jq reorders the contents so the diff is awful:
```
$ docker run -i --rm -v $(pwd):/work mikefarah/yq '.presubmits.kubevirt/kubevirt[] | pick(["name", "run_if_changed", "skip_if_only_changed"])' /work/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml 
name: pull-kubevirt-e2e-k8s-1.23-sig-compute-cgroupsv2
run_if_changed: pkg/virt-handler/cgroup/.*
name: pull-kubevirtci-bump-kubevirt
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-sig-storage-cgroupsv2
run_if_changed: pkg/virt-handler/cgroup/.*|pkg/virt-handler/hotplug-disk/.*|pkg/hotplug-disk/.*|cmd/virt-chroot/cgroup.go
name: pull-kubevirt-e2e-k8s-1.24-sig-compute-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-network-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-storage-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-storage-dv-gc
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-sig-performance
run_if_changed: ^pkg/virt-api/.*|^pkg/virt-handler/.*|^pkg/virt-controller/.*|^pkg/virt-launcher/.*
name: pull-kubevirt-e2e-k8s-1.24-operator-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-windows2016
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-kind-1.22-sriov-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-kind-1.22-sriov
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-kind-1.23-vgpu
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-kind-1.23-vgpu-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-check-tests-for-flakes
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-generate
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-verify-rpms
run_if_changed: WORKSPACE
name: pull-kubevirt-verify-go-mod
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-gosec
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-build
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-build-arm64
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-unit-test
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-goveralls
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-fossa
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-apidocs
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-client-python
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-manifests
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-prom-rules-verify
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-check-unassigned-tests
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-sig-network
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-ipv6-sig-network
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-sig-storage
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-sig-compute
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-compute-migrations
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-sig-compute-migrations
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-compute-migrations-nonroot
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-operator
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-sig-compute-realtime
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-arm64
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: build-kubevirt-builder
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-sig-network
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-code-lint
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-sig-storage
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-sig-compute
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-operator
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.23-swap-enabled
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.22-sig-monitoring
run_if_changed: ^pkg/monitoring/.*|tests/monitoring/.*$
name: pull-kubevirt-e2e-k8s-1.23-single-node
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-network
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-storage
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-sig-compute
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-operator
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-psa-sig-compute
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$
name: pull-kubevirt-e2e-k8s-1.24-psa-sig-storage
skip_if_only_changed: ^docs/|\\.(md|adoc)$|^(README|LICENSE|OWNERS|OWNERS_ALIASES)$

```

### CODE REVIEW

**Comment by rmohr** [comment]
prow does not support skipping required jobs with regex.

/hold

**Comment by lyarwood** [comment]
> prow does not support skipping required jobs with regex.
> 
> /hold

Gah apologies, there wasn't any suggestion of this in the [only docs I could find](https://pkg.go.dev/k8s.io/test-infra/prow/config#RegexpChangeMatcher). So I guess there's no way of doing this at the moment? If so I'll close this out.

**Comment by rmohr** [comment]
> Gah apologies, there wasn't any suggestion of this in the [only docs I could find](https://pkg.go.dev/k8s.io/test-infra/prow/config#RegexpChangeMatcher). So I guess there's no way of doing this at the moment? If so I'll close this out.

Yes, I fear we can't merge anything like this.

**Comment by lyarwood** [comment]
https://github.com/kubernetes/test-infra/blob/654386a21f6f378024dcedea7e6b167da0b25de7/prow/config/config.go#L2878-L2880 - ACK never mind, it was worth a try :)

**Pull request closed without merging**
