### PR TITLE
cnao, release 0.89: Add presubmits

### PR DESCRIPTION
**Pull request by oshoval**
Copied latest release presubmit file, changed to 0.89 all over.
Compared to main one, and took the relevant changes:
1. optional for dynamic networks
2. update bootstrap image

### CODE REVIEW

**Comment by phoracek** [comment]
/hold

@oshoval feel free to unhold when ready

**Comment by oshoval** [comment]
/hold 

based on previous release file, better to be based on main
diff from glance
1. bootstrap images
2. dynamic network as optional

**Comment by oshoval** [comment]
/hold cancel

did the above changes

**Comment by oshoval** [comment]
/rehearse

@phoracek
ptal

**Comment by oshoval** [comment]
all pass beside flaky dynamic networks which is optional
but since it is rehearse, on rehearse failure is blocked
so i pushed a zero change, ptal

we can also remove this lane if needed from 0.89

**Pull request merged**
