### PR TITLE
knmstate-jobs-release-0.47

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Review by rhrazdil — COMMENTED** [review]
Aren't we missing docs lane?

**Review by fgimenez — APPROVED** [review]
/approve
/hold

Feel free to unhold when ready

**Comment by qinqon** [comment]
/override rehearsal-pull-kubernetes-nmstate-e2e-handler-k8s-0.47

**Comment by fgimenez** [comment]
/override rehearsal-pull-kubernetes-nmstate-e2e-handler-k8s-0.47
/override rehearsal-pull-kubernetes-nmstate-e2e-handler-k8s-future-0.47
/override rehearsal-pull-kubernetes-nmstate-e2e-operator-k8s-0.47
/override rehearsal-pull-kubernetes-nmstate-unit-test-0.47

**Pull request merged**
