### PR TITLE
Enable DCO plugin for virtblocks org

### PR DESCRIPTION
**Pull request by rmohr**
Enable the DCO plugin for the virtblocks org.

### CODE REVIEW

**Comment by rmohr** [comment]
@andreabolognani let me know if you want this enabled. Just respond here and we can merge it.

**Comment by rmohr** [comment]
/approve

/hold

holding until @andreabolognani agreed to this.

**Comment by andreabolognani** [comment]
> @andreabolognani let me know if you want this enabled. Just respond here and we can merge it.

So IIUC this will cause the KubeVirt CI to verify `Signed-off-by` tags are present for each commit as required, and if so add the `dco-signoff: yes` label.

Will the submitter be notified automatically if the tags are not present, and told to add them?

Either way this definitely sounds like a good idea, so OK to merge from my side. Thanks!

**Comment by rmohr** [comment]
> So IIUC this will cause the KubeVirt CI to verify `Signed-off-by` tags are present for each commit as required, and if so add the `dco-signoff: yes` label.

This and it will also add a `dco` check to the ci status on the PR.

> Will the submitter be notified automatically if the tags are not present, and told to add them?

Yes, prow writes a comment to the PR which explains what the user will have to do. Once the PR is signed-off, prow will delete the comment (a general pattern by prow, to first inform the user, but then remove the noise again from the PR)

**Comment by andreabolognani** [comment]
> > So IIUC this will cause the KubeVirt CI to verify `Signed-off-by` tags are present for each commit as required, and if so add the `dco-signoff: yes` label.
> 
> This and it will also add a `dco` check to the ci status on the PR.
> 
> > Will the submitter be notified automatically if the tags are not present, and told to add them?
> 
> Yes, prow writes a comment to the PR which explains what the user will have to do. Once the PR is signed-off, prow will delete the comment (a general pattern by prow, to first inform the user, but then remove the noise again from the PR)

Sounds good, thanks for the explanation!

**Pull request merged**
