### PR TITLE
Document how to create jobs from local configurations

### PR DESCRIPTION
**Pull request by rmohr**

### CODE REVIEW

**Comment by slintes** [comment]
Didn't work, maybe the job manifest created by the tool isn't compatible with our prow version. Needs some investigation.
/hold

**Comment by cynepco3hahue** [comment]
@slintes Can you show the error that you got?

**Comment by cynepco3hahue** [comment]
I checked it locally and all worked fine, succeeded to create the prow job.
/lgtm

**Comment by slintes** [comment]
@cynepco3hahue I was able to create jobs, but they weren't executed. Did they for you?

**Comment by cynepco3hahue** [comment]
@slintes yes it worked for me and job started.

**Comment by rmohr** [comment]
Hm, @cynepco3hahue could you add the tag of the mkpj which you used? I guess that in the version which @slintes used a bug might exist, or it is not compatible with our prow version.

**Comment by cynepco3hahue** [comment]
@rmohr I used master one with the commit `ab25880be748bb3d20cfdcba86e4974fec36dbe6`

**Comment by rmohr** [comment]
@slintes @cynepco3hahue this PR should work now too. The reason why it did not work before was that we were on an old prow version which did not support setting things like `5m` for grace periods. Works now with #104 merged.

**Pull request merged**
