### PR TITLE
Add orelmisan to the organization

### PR DESCRIPTION
**Pull request by orelmisan**
# @orelmisan
## Requirements
- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
- [x] I am actively contributing to KubeVirt
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
- [x] I have publicly introduced myself to the community through one of the community communication channels (https://github.com/kubevirt/community#socializing)

## Sponsors
* @AlonaKaplan 
* @EdDev 

### PRs reviewed and/or authored
- https://github.com/kubevirt/kubevirt/pull/6766
- https://github.com/kubevirt/kubevirt/pull/6774
- https://github.com/kubevirt/kubevirt/pull/6797
- https://github.com/kubevirt/kubevirt/pull/6838
- https://github.com/kubevirt/kubevirt/pull/6856

### Issues responded to
Signed-off-by: Orel Misan <omisan@redhat.com>

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
Welcome Orel!

**Review by enp0s3 — APPROVED** [review]
@orelmisan Welcome aboard!
/approve

**Pull request merged**
