### PR TITLE
periodic-kubevirtci-bump-kubevirt, Add what changed info to automatic bumps

### PR DESCRIPTION
**Pull request by oshoval**
Add support of commit description command,
this way, the created PR can have an informative
commit message and PR description.

Use this new feature in order to add what changed info to automatic bumps

Depends on https://github.com/kubevirt/kubevirt/pull/6306

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
/hold
depends on 
https://github.com/kubevirt/kubevirt/pull/6306

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by fgimenez — APPROVED** [review]
/hold
/approve

Thanks! Feel free to unhold when ready.

**Comment by oshoval** [comment]
/hold cancel

6306 was merged

**Pull request merged**
