### PR TITLE
macvtap-cni: rename the main branch

### PR DESCRIPTION
**Pull request by maiqueb**
The `macvtap-cni` repo has been renamed from `master` to `main`.

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by fgimenez** [comment]
Do we need to change the branch-protector config? Here https://github.com/kubevirt/project-infra/blob/master/github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml#L310

**Comment by maiqueb** [comment]
> Do we need to change the branch-protector config? Here https://github.com/kubevirt/project-infra/blob/master/github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml#L310

While I have absolutely no idea on what that does, it doesn't make sense to protect a branch that doesn't exist. 
And if we protect something, well, might as well protect the one branch that does.

**Comment by fgimenez** [comment]
Here is a small explanation of branch protector in Prow https://github.com/kyma-project/test-infra/blob/main/docs/prow/prow-architecture.md#branch-protector basically enforces the branch protection settings for the given repos, similar to what you get by configuring branch protection in the repo itself through the UI.

**Review by fgimenez — APPROVED** [review]
/approve

**Comment by fgimenez** [comment]
branch-protector was already changed, sorry for the noise :)

**Comment by maiqueb** [comment]
> branch-protector was already changed, sorry for the noise :)

No problem at all; this made me learn something :) 

Thanks.

**Pull request merged**
