### PR TITLE
phased plugin: Enable from-branch-protection for kubevirt/kubevirt main

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Enable `from-branch-protection`.
Removes `run_before_merge` workaround.
Now that Tide bug was solved, Tide should detect manually required jobs
as required with those fixes, as if they had `run_before_merge`.

To be merged only when we update tide to a version that includes
https://github.com/kubernetes/test-infra/pull/31687 (done)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
Seems we now have the needed fix
https://github.com/kubevirt/project-infra/pull/3252
(PR was merged on 3 Feb)

**Comment by oshoval** [comment]
/cc @brianmcarey @dhiller 

can you please take a look ?

**Review by dhiller — COMMENTED** [review]
/approve

@oshoval why is this still draft? Is there something to do left?

**Comment by oshoval** [comment]
Nope, it is ready now, we will just need to keep an eye to see it works as expected
Undrafting
Thanks

**Comment by oshoval** [comment]
/cc @brianmcarey 
can you please take a look ?

**Review by brianmcarey — COMMENTED** [review]
/lgtm

thanks for chasing this up @oshoval !

**Pull request merged**
