### PR TITLE
Fix cnao release0.76 lanes

### PR DESCRIPTION
**Pull request by RamLavi**
This PR removes knmstate lane from the release0.76 stable branch
Also updates the CI image.

### CODE REVIEW

**Comment by RamLavi** [comment]
@dhiller is `quay.io/kubevirtci/bootstrap:v20220211-d7d6c59` the best image to use?

**Comment by dhiller** [comment]
> @dhiller is quay.io/kubevirtci/bootstrap:v20220211-d7d6c59 the best image to use?

We have a new one (see https://github.com/kubevirt/project-infra/pull/2098) that you can also use, based on Fedora 36.

In general we update the jobs with the latest images on a weekly basis, so you would not need to worry about the images getting stale.

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
