### PR TITLE
Reduce memory requests for e2e jobs

### PR DESCRIPTION
**Pull request by fgimenez**
Also removes stale 1.20 jobs.

/cc @rmohr @dhiller 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve
/hold

Quick question: I forgot how we ensure that every test is run on at least one lane?

**Comment by fgimenez** [comment]
> Quick question: I forgot how we ensure that every test is run on at least one lane?

Very good question, I think we don't have a way to verify this at the moment. I think it would be possible to have a lane that tests on a periodic (or even presubmit, it would be very quick) that a dry-run execution without any `SKIP` returns no tests, wdyt?

As a reference, I wrote something similar when we were planning to run quarantine lanes on presubmits https://github.com/kubevirt/kubevirt/commit/5b96b8dd49a1f48b038fc992dee45d757b086bb0#diff-6d65ed5c750019a199c61a33ea9202fb727c05e257560f38f014e6b1520e50ed

**Comment by fgimenez** [comment]
> > Quick question: I forgot how we ensure that every test is run on at least one lane?
> 
> Very good question, I think we don't have a way to verify this at the moment. I think it would be possible to have a lane that tests on a periodic (or even presubmit, it would be very quick) that a dry-run execution without any `SKIP` returns no tests, wdyt?
> 
> As a reference, I wrote something similar when we were planning to run quarantine lanes on presubmits [kubevirt/kubevirt@5b96b8d#diff-6d65ed5c750019a199c61a33ea9202fb727c05e257560f38f014e6b1520e50ed](https://github.com/kubevirt/kubevirt/commit/5b96b8dd49a1f48b038fc992dee45d757b086bb0#diff-6d65ed5c750019a199c61a33ea9202fb727c05e257560f38f014e6b1520e50ed)

I've proposed https://github.com/kubevirt/kubevirt/pull/5748 and https://github.com/kubevirt/project-infra/pull/1271 to fix this issue. Is it ok to unhold this one?

**Comment by dhiller** [comment]
> > > Quick question: I forgot how we ensure that every test is run on at least one lane?
> > 
> > 
> > Very good question, I think we don't have a way to verify this at the moment. I think it would be possible to have a lane that tests on a periodic (or even presubmit, it would be very quick) that a dry-run execution without any `SKIP` returns no tests, wdyt?
> > As a reference, I wrote something similar when we were planning to run quarantine lanes on presubmits [kubevirt/kubevirt@5b96b8d#diff-6d65ed5c750019a199c61a33ea9202fb727c05e257560f38f014e6b1520e50ed](https://github.com/kubevirt/kubevirt/commit/5b96b8dd49a1f48b038fc992dee45d757b086bb0#diff-6d65ed5c750019a199c61a33ea9202fb727c05e257560f38f014e6b1520e50ed)
> 
> I've proposed [kubevirt/kubevirt#5748](https://github.com/kubevirt/kubevirt/pull/5748) and #1271 to fix this issue. Is it ok to unhold this one?

SGTM!

/unhold

**Pull request merged**
