### PR TITLE
Add nightly job exercising conformance tests

### PR DESCRIPTION
**Pull request by phoracek**
Run KubeVirt conformance tests every night.

Exercised tests: https://github.com/kubevirt/kubevirt/pull/4115

### CODE REVIEW

**Comment by RamLavi** [comment]
can rehearsal be used to check this once [kubevirt/kubevirt#4115](https://github.com/kubevirt/kubevirt/pull/4115) passes?

**Comment by phoracek** [comment]
We don't have a rehearsal job for it, or can we use the existing one to test this? I'm not so familiar with it.

If not, it may be worth adding one.

/hold

**Comment by danielBelenky** [comment]
@phoracek can we merge this?

**Comment by phoracek** [comment]
@danielBelenky the test PR is still open. Let's wait on this one, so we don't get nightly alarms about failing lane. I'd also like to add a rehearsal job for it, although I don't know how yet.

**Comment by danielBelenky** [comment]
@petrkotas we still don't really support rehearsals like openshift-ci does.
I wrote the plugin but I still didn't get the time to actually properly deploy it :(

**Comment by phoracek** [comment]
I see, thanks for heads up. Then let's just merge the kubevirt PR and then get this in, and see if it works at night :eyes:

**Comment by phoracek** [comment]
The PR was merged, we can give this one a chance

**Pull request merged**
