### PR TITLE
capk: sonobuoy conformance lane

### PR DESCRIPTION
**Pull request by rhrazdil**
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
what would you think about using the `optional: false` setting initially. Just until we feel comfortable that this set of tests is stable?

**Comment by rhrazdil** [comment]
>what would you think about using the optional: true setting initially. Just until we feel comfortable that this set of tests is stable?

Sure, added the optional attribute.

**Comment by rhrazdil** [comment]
I'm not sure why the rehearsal job isn't running now

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
