### PR TITLE
Job modifications required for removing manual steps from kubevirtci

### PR DESCRIPTION
**Pull request by rmohr**
Removes:

 * openshift jobs
 * e2e jobs for k8s version which are EOL
 * All push jobs
 
Makes all check-provision jobs for supported k8s version required

Adds a publish job which will publish kubevirtci after each merge.

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/lgtm
/approve
/hold in case someone else wants to have a look

**Review by jean-edouard — APPROVED** [review]

**Comment by rmohr** [comment]
/hold

Needs to be coordinated with https://github.com/kubevirt/kubevirtci/pull/452

**Comment by qinqon** [comment]
/lgtm

We already depend on google cloud and it simplify stuff.

**Pull request merged**
