### PR TITLE
Add KubeVirt Velero plugin repository and team

### PR DESCRIPTION
**Pull request by tomob**
Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>

### CODE REVIEW

**Comment by tomob** [comment]
@phoracek @fgimenez Are there any additional requirements I would have to meet to have the repo imported in the KubeVirt org?

**Comment by phoracek** [comment]
I'm not that savvy of Prow to be able to tell. @fgimenez ?

**Comment by fgimenez** [comment]
In terms of peribolos requirements I think the changes in this PR are enough, is that correct @dhiller ?

**Review by dhiller — APPROVED** [review]
/approve

In terms of automation of branch-protection and automatic merges with tide we would need to add things here, but for a first repo creation this is good enough.

Example for the required configuration mentioned is here: https://github.com/kubevirt/project-infra/commit/ef2b64a66bb36868bbf43964ab58c3776e75c519

**Comment by dhiller** [comment]
> /approve
> 
> In terms of automation of branch-protection and automatic merges with tide we would need to add things here, but for a first repo creation this is good enough.
> 
> Example for the required configuration mentioned is here: [ef2b64a](https://github.com/kubevirt/project-infra/commit/ef2b64a66bb36868bbf43964ab58c3776e75c519)

@tomob if you need it, I've created a doc on how to enable automation of merges here: https://github.com/kubevirt/community/pull/119

**Pull request merged**
