### PR TITLE
issues/1139...Consolidate kubevirt.github.io files for disk img builds

### LINKED ISSUE #1139: Move kubevirt.github.io config files to project-infra
Move kubevirt.github.io config bits to project-infra

This will enable the following ...
* kubevirt.github.io repo contains only content, Makefile, Community files (LICENSE, GUIDELINES, etc)
* Pieces used to assemble the container disk img will sit right next to each the Dockerfile.

The following files should be moved ...
* Jekyll config _config.yml
* Ruby Gemfile
* Casperjs check_selectors.js
* Rakefile
* SELinux module files for enabling SELinux enabled containers when running on a Virtual Box vm with a vboxsf mount.  These files have been in my local repo.  They really need to be added to some repo.

### PR DESCRIPTION
**Pull request by mazzystr**
Fixes #1139 issues/1139

### CODE REVIEW

**Comment by mazzystr** [comment]
@dhiller I don't need build-bootstrap-image for this directory.  We're good to merge.

**Review by dhiller — COMMENTED** [review]
So I understand you don't need a publishing job like `publish-kubevirt-userguide-image`, right?

/lgtm
/approve
/hold

Remove hold when ready (or ping me)

**Comment by mazzystr** [comment]
@dhiller Correct but this or is for website / kubevirt.github.io components.

Hold can be removed.

**Comment by mazzystr** [comment]
@dhiller I don't have rights to add/remove labels on this repo

**Review by dhiller — APPROVED** [review]
/unhold

**Pull request merged**
