### PR TITLE
Add dominikholler to org members

### PR DESCRIPTION
**Pull request by dominikholler**
I am going to contribute to kubevirt.

### CODE REVIEW

**Review by fgimenez — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by rmohr** [comment]
/hold

@dominikholler in order to join the org, can you have a look and read through https://github.com/kubevirt/community/tree/master/member_dd ?

**Comment by dominikholler** [comment]
> @dominikholler in order to join the org, can you have a look and read through https://github.com/kubevirt/community/tree/master/member_dd ?

Yes, I just did not notice the checklist on similar PRs.
But let's be formal more or less correct:

## Requirements

[X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[X] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[ongoing] I am actively contributing to KubeVirt<br>
[hopefully ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[ ] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[X] I have publicly introduced myself to the community through one of the community communication channels: last weeks KubeVirt Community Weekly Meeting<br>

(https://github.com/kubevirt/community#socializing)

## List of contributions to the KubeVirt project

- https://github.com/kubevirt/ssp-operator/pull/184
- https://github.com/kubevirt/common-templates/pull/363
- https://github.com/kubevirt/community/pull/114

**Pull request merged**
