### PR TITLE
Allow rerun capk e2e + bump golang to 1.20

### PR DESCRIPTION
**Pull request by nunnatsa**

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve
/hold

remove the hold when you're ready for this to go in

**Comment by nunnatsa** [comment]
@dhiller - will this change allow us to rerun the test?

Right now we can only close&open the PR, push a new commit or ask someone with privilege to rerun.

**Comment by dhiller** [comment]
^^ @nunnatsa

**Comment by dhiller** [comment]
@nunnatsa first thing you could do is to check whether there's a webhook entry looking like this: 
image

**Comment by dhiller** [comment]
In a nutshell: if the GitHub webhook is installed prow.ci.kubevirt.io will not get notified by comments on a PR from this repository.

I am confused why the e2e job is triggered on a PR push, since I thought without GitHub webhook this wasn't possible. @rmohr can you chime in why this works?

**Comment by nunnatsa** [comment]
> In a nutshell: if the GitHub webhook is not installed [prow.ci.kubevirt.io](https://prow.ci.kubevirt.io) will not get notified by comments on a PR from this repository.
> 
> I am confused why the e2e job is triggered on a PR push, since I thought without GitHub webhook this wasn't possible. @rmohr can you chime in why this works?



> In a nutshell: if the GitHub webhook is not installed [prow.ci.kubevirt.io](https://prow.ci.kubevirt.io) will not get notified by comments on a PR from this repository.
> 
> I am confused why the e2e job is triggered on a PR push, since I thought without GitHub webhook this wasn't possible. @rmohr can you chime in why this works?

@dhiller - the trigger is done from a github action, here: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/1dd9702d39733f6cb7485fc049e12e52b129960a/.github/workflows/e2e.yaml

I'm not sure it's possible to do it with a webhook

**Comment by nunnatsa** [comment]
I don't think it'll work

**Pull request closed without merging**
