### PR TITLE
dra-pci-driver: update team config in orgs.yaml

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Fixes a spelling error in the configuration for the maintainer team.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/cc @alicefr

### CODE REVIEW

**Comment by victortoso** [comment]
/lgtm

Typos-- :)

**Comment by alicefr** [comment]
Sooorry

**Comment by dhiller** [comment]
> Sooorry

All good :smile:

**Pull request merged**
