### PR TITLE
csi-driver presumbits: Correct e2e test lane

### PR DESCRIPTION
**Pull request by brybacki**
Correct the e2e test lane to execute functional tests

Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

### CODE REVIEW

**Comment by brybacki** [comment]
checking, maybe it runs on default now,
I think I can add a script in csi-driver repo that setups lane variables

**Comment by davidvossel** [comment]
> I forget where do we set the kubevirtci KUBEVIRT_PROVIDER environment variable? In other words how does it know its 1.23

The kubevirtci script does this. I think for now one lane that defaults to whatever we're using in by default in the dev environment is fine. It's kind of complicated because there are actually 2 diminsions here, the infra k8s version and the guest k8s version. Right now i think infra is 1.23 but guest is 1.22. We'll eventually want some more flexibility in expressing exactly what we want, but we don't have that at the moment.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Comment by awels** [comment]
So if not specified it defaults to something in kubevirtci? Interesting didn't know that.

**Comment by brybacki** [comment]
Actually we set most of the things in ./kubevirtci script 

Anyway this can be a start for some scripts to use in nex versiosn: https://github.com/kubevirt/csi-driver/pull/51

**Comment by awels** [comment]
Gotcha, didn't realize there was a script in the csi-driver repo that sets it all.
/lgtm
/approve

**Comment by brybacki** [comment]
Added testgrid-dashboards: `kubevirt-csi-driver-presubmits`
before it was shown on `kubevirt`

**Comment by brybacki** [comment]
how to read that test failure pull-project-infra-prow-deploy-test?

**Comment by awels** [comment]
I am not sure how to read it, lets try it again
/test pull-project-infra-prow-deploy-test

**Comment by awels** [comment]
looks like it was just a fluke
/lgtm

**Pull request merged**
