### PR TITLE
Add jobs for okd-4.1.0-rc.4

### PR DESCRIPTION
**Pull request by rmohr**
Add build jobs for okd-4.1.0-rc.4

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@rmohr @davidvossel I believe we should just update `kubevirtci` repo to have folder 4.1 without the minor release version to prevent create additional prow jobs and providers.

**Comment by rmohr** [comment]
@cynepco3hahue you are probably right. It does not make sense to keep old release candidates.

**Comment by davidvossel** [comment]
>  I believe we should just update kubevirtci repo to have folder 4.1 without the minor release version to prevent create additional prow jobs and providers.

works for me. I'll update the PR.

**Comment by davidvossel** [comment]
> works for me. I'll update the PR.

actually, i won't update the PR, i forgot I didn't submit this one.

**Comment by slintes** [comment]
closing for https://github.com/kubevirt/project-infra/pull/114

**Pull request closed without merging**
