### PR TITLE
add aerosouund to the KubeVirt org

### PR DESCRIPTION
**Pull request by aerosouund**
# GitHub Username: @aerosouund

## Requirements

- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
- [x] I am actively contributing to KubeVirt
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
- [x] I have publicly introduced myself to the community through one of the community communication channels

## Sponsors

* @dhiller 
* @brianmcarey 

## List of contributions to the KubeVirt project

* PRs reviewed and/or authored
- https://github.com/kubevirt/kubevirtci/pull/1217
- https://github.com/kubevirt/kubevirtci/pull/1209
- https://github.com/kubevirt/kubevirtci/pull/1255
- https://github.com/kubevirt/kubevirtci/pull/1230
- https://github.com/kubevirt/kubevirtci/pull/1247

* Issues responded to
- https://github.com/kubevirt/kubevirtci/issues/1222
- https://github.com/kubevirt/kubevirtci/issues/1110
- https://github.com/kubevirt/kubevirtci/issues/1185

### CODE REVIEW

**Comment by victortoso** [comment]
+1
/lgtm

**Comment by acardace** [comment]
/lgtm 
Welcome and thank you for your amazing contributions so far!

**Comment by aerosouund** [comment]
Thanks alot everyone ❤️

**Pull request merged**
