### PR TITLE
Move kubevirtci prowjobs to new workloads cluster

### PR DESCRIPTION
**Pull request by brianmcarey**
/cc @dhiller

### CODE REVIEW

**Comment by brianmcarey** [comment]
There looks to be an issue with the centos8 providers and another issue deleting a test namespace on the 1.27 provider. These issues are seen on both clusters.

**Comment by brianmcarey** [comment]
@dhiller the issues here are not host cluster related as they are seen on both clusters - are we ok to take this in?

**Comment by dhiller** [comment]
> @dhiller the issues here are not host cluster related as they are seen on both clusters - are we ok to take this in?

Yes, agreed.

/lgtm
/approve

**Pull request merged**
