### PR TITLE
Build multiarch bootstrap image as part of postsubmit job

### PR DESCRIPTION
**Pull request by brianmcarey**
Only building the multiarch bootstrap image periodically causes inconsistencies which can cause issues with image mismatches.

This change removes the periodic build job and enables the multiarch build in the postsubmit job.

Also updates publish script to use podman rather than docker.

/cc @zhlhahaha @dhiller 

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Comment by brianmcarey** [comment]
/hold 

Testing locally with phaino

**Comment by brianmcarey** [comment]
Local test run completed successfully 

/unhold

**Review by dhiller — APPROVED** [review]
/approve

Thanks for taking this, @brianmcarey !

**Pull request merged**
