### PR TITLE
A new fedora based bootstrap image

### PR DESCRIPTION
**Pull request by rmohr**
Pull in the test-infra boostrap image from https://github.com/kubernetes/test-infra/commit/7e74b33534f950170801fb3ce015c1e96c975471 and rework it to work with fedora.

The image is updated extremely seldom, so we don't miss much but can in contrast gain:

 * streight forward modifications (ca updates, adding bazelisk, ...)
 * much newer glibc versions than which exist in debian and the freedom to easier change these if needed

Unblocks #835 which needs new enough glibc versions.

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

Forgot some debian bits in the bazel cache file

**Review by fgimenez — APPROVED** [review]
/lgtm
/approve

thx!

**Pull request merged**
