### PR TITLE
Enable NodeRestriction fg for 1.30 lanes

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
Enable NodeRestriction fg for 1.30 lanes
This allow us to get wider feedback on the
feature.

Ref https://github.com/kubevirt/kubevirt/pull/12009

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
I don't see an effect on tests requiring this feature gate being executed - likely the fg `ServiceAccountTokenPodNodeInfo` needs to get enabled as documented in KV source - I don't know whether that has happened inside KubeVirtCI?

**Comment by dhiller** [comment]
^^ @xpivarc

**Comment by xpivarc** [comment]
> I don't see an effect on tests requiring this feature gate being executed - likely the fg `ServiceAccountTokenPodNodeInfo` needs to get enabled as documented in KV source - I don't know whether that has happened inside KubeVirtCI?

1.30 lanes has this by default because it is in Beta there.

**Comment by xpivarc** [comment]
ping @dhiller @brianmcarey

**Review by brianmcarey — APPROVED** [review]
/approve

/hold

It could be good to communicate this on kubevirt-dev as we are enabling this across sig lanes.

**Comment by brianmcarey** [comment]
@xpivarc  - maybe we should enable the NodeRestriction feature gate in the kubevirtci provider to be consistent with the others?  https://github.com/kubevirt/kubevirtci/blob/aa7d876ffa160cca3132d760328b248ce8122f50/cluster-provision/k8s/1.30/nodes.sh#L54

**Pull request merged**
