### PR TITLE
Update nmstate presubmit to use podman bootstrap

### PR DESCRIPTION
**Pull request by brianmcarey**
/cc @qinqon @rhrazdil 

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Comment by brianmcarey** [comment]
@qinqon I guess `pull-nmstate-integ_tier1-k8s` is no longer used? Will i go ahead and remove the config?

**Comment by qinqon** [comment]
> @qinqon I guess `pull-nmstate-integ_tier1-k8s` is no longer used? Will i go ahead and remove the config? 

It is it was fixed by nmstate team a week ago, we have to check why is failing.

**Comment by brianmcarey** [comment]
> 
> It is it was fixed by nmstate team a week ago, we have to check why is failing.

It might just be an issue with the rehearsal plugin - the job is looking for a `main` branch which doesn't exist in the nmstate project - the default branch is called `base`. I will see if I can test this another way.

**Comment by brianmcarey** [comment]
Yes - ran succesfully here with podman so it looks good - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/nmstate_nmstate/2070/pull-nmstate-integ_tier1-k8s/1583372208846147584

**Comment by brianmcarey** [comment]
> > @qinqon I guess `pull-nmstate-integ_tier1-k8s` is no longer used? Will i go ahead and remove the config?
> 
> It is it was fixed by nmstate team a week ago, we have to check why is failing.

Its an issue with the version of the rehearsal plugin that is deployed - it is quite old (`quay.io/kubevirtci/rehearse:v20200923-8930f83`) and doesn't contain the change to detect the default branch.

I am trying to get a newer version deployed but I don't think that we need to wait for that here?

**Pull request merged**
