### PR TITLE
Add the deprecation notice to  label `triage/build-watcher`

### LINKED ISSUE #3653: deprecate label triage/build-watcher and associated job
We maintain our GitHub label definitions in the [labels.yaml] - the definitions in GitHub are updated periodically after any change to that file.

The label [triage/build-watcher] has not been used for more that three years [1] - it is currently superceded by the sig/ci label, which is tracking qurantine and infra stuff. Thus we should add a deprecation notice.

Suggestion: prefix the description [2] of the label with `DEPRECATED:`, which should make it clear that this label should not be used any more.

The commenter periodic job definition [3] can then be removed.

/kind tracker
/priority backlog

[labels.yaml]: https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
[triage/build-watcher]: https://github.com/kubevirt/project-infra/blob/main/docs/labels.md#triage/build-watcher
[1]: https://github.com/search?q=org%3Akubevirt+is%3Aissue+label%3Atriage%2Fbuild-watcher&type=issues&s=updated&o=desc
[2]: https://github.com/kubevirt/project-infra/blob/3be67a4d732dc9d02bf6ab2c67dae28088aaeec6/github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml#L33
[3]: https://github.com/kubevirt/project-infra/blob/56e48d9a03f31a5558d26c312b5dee40ce5fb4ca/github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml#L73-L100

### PR DESCRIPTION
**Pull request by anishbista60**
**What this PR does / why we need it**:
- Add the deprecation notice to  label `triage/build-watcher`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3653 

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by anishbista60** [comment]
@dhiller

**Comment by anishbista60** [comment]
here also for hold till october 1st . For `hacktoberfest`

**Comment by anishbista60** [comment]
@dhiller please unhold it.

**Comment by anishbista60** [comment]
needs LGTM label.

**Review by dhiller — APPROVED** [review]

**Pull request merged**
