### PR TITLE
Integrate kubevirt/libguestfs-appliance

### PR DESCRIPTION
**Pull request by rmohr**

### CODE REVIEW

**Review by dhiller — CHANGES_REQUESTED** [review]
Looks good in general, although I am missing the changes within `orgs.yaml` that would let peribolos create the repository as described here: https://github.com/kubevirt/community/blob/master/docs/automating-github-org-management.md

**Comment by rmohr** [comment]
> Looks good in general, although I am missing the changes within `orgs.yaml` that would let peribolos create the repository as described here: https://github.com/kubevirt/community/blob/master/docs/automating-github-org-management.md

Thx. Should be done now.

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
