### PR TITLE
Change the multus 1.13.3 to 1.15.1

### PR DESCRIPTION
**Pull request by SchSeba**
This PR change the 1.13.3 provider to the new one.

The PR is for the kubevirt project.

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/project-infra/197)

### CODE REVIEW

**Comment by SchSeba** [comment]
/hold 

need to update the kubevirtci project hash in the kubevirt project first using this PR https://github.com/kubevirt/kubevirtci/pull/147

**Comment by SchSeba** [comment]
@cynepco3hahue this looks unrelated https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/197/pull-project-infra-test-flakefinder/1176801512270073857

**Comment by rmohr** [comment]
@SchSeba jobs are green now.

**Comment by rmohr** [comment]
@qinqon @phoracek is this now obsolet with the cnao provider?

**Comment by qinqon** [comment]
@rmohr yes multus is already updated as part of effort of the cnao lane.

**Pull request closed without merging**
