### PR TITLE
Add headBranch support to git-pr.sh

### PR DESCRIPTION
**Pull request by fgimenez**
We are getting errors in periodic-kubevirtci-cluster-minorversion-updater, for instance https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1432736830964371456. The job doesn't find an existing PR to update and later fails to create it bc it is already there.

Looks like GH query is failing with the truncated title here https://github.com/kubevirt/kubevirtci/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+repo%3Akubevirt%2Fkubevirtci+author%3Akubevirt-bot+in%3Atitle+Run+bazelisk+run+%2F%2Frobots%2Fcmd%2Fkubevirtci-bumper%3Akubevirtci-bumper+--+-ensure-latest+--k8s-provider-dir+%2Fhome%2Fprow%2Fgo%2Fsrc%2Fgithub.com%2Fkubevirt%2Fproject-i but not if we get a bit more of the title https://github.com/kubevirt/kubevirtci/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+repo%3Akubevirt%2Fkubevirtci+author%3Akubevirt-bot+in%3Atitle+Run+bazelisk+run+%2F%2Frobots%2Fcmd%2Fkubevirtci-bumper%3Akubevirtci-bumper+--+-ensure-latest+--k8s-provider-dir+%2Fhome%2Fprow%2Fgo%2Fsrc%2Fgithub.com%2Fkubevirt%2Fproject-infra

 Instead of depending on match-title, with these changes we use the head-branch option that looks for a specific branch from which the PR will be created.

/cc @dhiller  

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve

While this will work, maybe we should add support for the headBranch flag, as I guess this will be much more stable: https://github.com/kubernetes/test-infra/blob/master/robots/pr-creator/main.go#L89

**Comment by fgimenez** [comment]
> While this will work, maybe we should add support for the headBranch flag in `hack/git-pr.sh`, as I guess this will be much more stable: https://github.com/kubernetes/test-infra/blob/master/robots/pr-creator/main.go#L89

Absolutely, thanks for pointing that out! I've updated the PR to add headBranch support, successfully executed here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-minorversion-updater/1432984048732475392 (although the PR title in https://github.com/kubevirt/kubevirtci/pull/655 was changed to reflect execution from my branch), PTAL.

**Review by dhiller — APPROVED** [review]
Thanks!

**Comment by oshoval** [comment]
Thanks, it seems we are using old version of pr-creator which doesn't support `--head-branch`
need to use the new pr-creator that Daniel H created i guess ?
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-bump-kubevirt/1434305420469473280

**Comment by fgimenez** [comment]
Indeed, thanks for the heads up, should be fixed with https://github.com/kubevirt/project-infra/pull/1539/

**Pull request merged**
