### PR TITLE
Add dteplits to the organization

### PR DESCRIPTION
**Pull request by dteplits**
# @dteplits

## Requirements

- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
- [x] I am actively contributing to KubeVirt<br>
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
- [x] I have publicly introduced myself to the community through one of the community communication channels<br>(https://github.com/kubevirt/community#socializing)

## Sponsors

* @AlonaKaplan
* @maiqueb 

## List of contributions to the KubeVirt project

 **PRs reviewed and/or authored** 

- https://github.com/kubevirt/kubevirt/pull/7074
- https://github.com/kubevirt/kubevirt/pull/7051
- https://github.com/kubevirt/kubevirt/pull/7023
- https://github.com/kubevirt/kubevirt/pull/6833

 **Issues responded to** 
- https://github.com/kubevirt/kubevirt/issues/6538

Signed-off-by: Diana Teplits [dteplits@redhat.com](mailto:dteplits@redhat.com)

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
ACK on sponsoring @dteplits .

**Comment by dteplits** [comment]
@phoracek

**Pull request merged**
