### PR TITLE
WIP, check same style with comma

### PR DESCRIPTION
**Pull request by oshoval**
Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
@fgimenez 
Hi, do you know maybe please why rehearsal doesn't work ?
it used to work, is it disabled or something?

Thanks

**Comment by fgimenez** [comment]
/rehearse

Trying again, there was an error in the rehearse pod logs that should be fixed now

**Comment by oshoval** [comment]
Nice works now
thanks
what was the problem>

**Comment by oshoval** [comment]
it did its job, it allocated 2 PFs, all the tests are failing, i think its because we are using the old sriov operator, which we are going to replace, going to run several times, just to make sure its stable

/rehearse

**Comment by oshoval** [comment]
1/2 pass

/rehearse

**Comment by oshoval** [comment]
First time i see this
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1013/rehearsal-pull-kubevirt-e2e-kind-1.17-sriov/1369577254916460544

but i don't think its related to this PR
anyhow the ditching of sriov-operator is on fire, so it doesn't worth investigating it until then

**Pull request closed without merging**
