### PR TITLE
Set the 1.24 lanes to required

### PR DESCRIPTION
**Pull request by brianmcarey**
/cc @dhiller @oshoval 

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by dhiller** [comment]
I figure that you are aware that automation exists for this cycle. So what is the reasoning to go ahead of the usual trail here?

**Comment by oshoval** [comment]
> I figure that you are aware that automation exists for this cycle. So what is the reasoning to go ahead of the usual trail here?

You might posted on the wrong PR ?

**Comment by dhiller** [comment]
> > I figure that you are aware that automation exists for this cycle. So what is the reasoning to go ahead of the usual trail here?
> 
> You might posted on the wrong PR ?

@oshoval ICYMI I was referring to [this automation](https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/K8S_AUTOMATION.md)

**Pull request merged**
