### PR TITLE
Add presubmit job for stable OVS CNI 0.19

### PR DESCRIPTION
**Pull request by phoracek**
Signed-off-by: Petr Horáček <phoracek@redhat.com>

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by oshoval** [comment]
@qinqon can you take a look please on the PR of Petr ?

**Comment by oshoval** [comment]
Thanks Quique, it seems only Petr and Alona have permissions
@AlonaKaplan can you take a look please?

**Comment by phoracek** [comment]
Taking Quique's approve as second LGTM.

/approve

**Pull request merged**
