### PR TITLE
bridge-marker, Add postsubmits

### PR DESCRIPTION
**Pull request by RamLavi**
added postsubmits to replace local travis [script](https://github.com/kubevirt/bridge-marker/blob/main/.travis.yml).

### CODE REVIEW

**Comment by RamLavi** [comment]
note that `main-bridge-marker` may help us running nightly builds in the future.

**Comment by RamLavi** [comment]
/hold
until a PR is in place on bridge marker to:
- remove the current travis script.
- add the infra to push using virtual tag.

**Comment by RamLavi** [comment]
/hold cancel
bridge-marker [PR](https://github.com/kubevirt/bridge-marker/pull/24) merged

**Comment by RamLavi** [comment]
Hey @fedepaol this PR is very similar to #1334
If the issue still exist on the lane and is not related to the PR, could you possible override it here as well?

**Comment by fedepaol** [comment]
> Hey @fedepaol this PR is very similar to #1334
> If the issue still exist on the lane and is not related to the PR, could you possible override it here as well?

Wrong Federico I think

**Comment by RamLavi** [comment]
> > Hey @fedepaol this PR is very similar to #1334
> > If the issue still exist on the lane and is not related to the PR, could you possible override it here as well?
> 
> Wrong Federico I think

ah sorry! :)

**Comment by RamLavi** [comment]
Hey @fgimenez this PR is very similar to #1334
If the issue still exist on the lane and is not related to the PR, could you possible override it here as well?

**Pull request merged**
