### PR TITLE
kubevirt,presubmit: Stop reporting failing arm64 unit tests

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

The ARM64 unit test lane is failing consistently[1] - stop reporting these failures on PRs to reduce noise and as the lane is optional.

This will allow time for investigation into the failures.

[1] https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-unit-test-arm64

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/cc @zhlhahaha @dhiller 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
/lgtm
I just run the unit tests on my local arm64 servers. All tests passes. I think the issue may related to cross compiling, I will give it a try to run the tests on x86_64 platform.

**Comment by brianmcarey** [comment]
> /lgtm I just run the unit tests on my local arm64 servers. All tests passes. I think the issue may related to cross compiling, I will give it a try to run the tests on x86_64 platform.

This lane runs on the arm64 cluster though?

**Comment by zhlhahaha** [comment]
> > /lgtm I just run the unit tests on my local arm64 servers. All tests passes. I think the issue may related to cross compiling, I will give it a try to run the tests on x86_64 platform.
> 
> This lane runs on the arm64 cluster though?

Yes, my fault, the unit tests run on arm64 server. It is strange, I can not reproduce the issue on my local server.

**Comment by zhlhahaha** [comment]
> > /lgtm I just run the unit tests on my local arm64 servers. All tests passes. I think the issue may related to cross compiling, I will give it a try to run the tests on x86_64 platform.
> 
> This lane runs on the arm64 cluster though?

I have an initial guess, this issue may related to `image: quay.io/kubevirtci/bootstrap:v20240711-f55d15c`,  it seems that tests start to fail when the bootstrap image update to v20240711-f55d15c.

**Review by dhiller — COMMENTED** [review]
/approve

**Pull request merged**
