### PR TITLE
Define periodics for quarantine runs

### PR DESCRIPTION
**Pull request by fgimenez**
* Removes old presubmit quarantine lanes
* Adds environment variable for the existing periodic jobs to work with the new logic.
* Adds periodics for CNAO, SRIOV and rook-ceph lanes

/cc @dhiller @rmohr 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by rmohr — COMMENTED** [review]
This will make the periodics fail pretty often by default. I am not sure I like that.

**Comment by fgimenez** [comment]
Indeed, we can create separate periodic lanes to run the stable suite, the ones in this PR will allow us to define when a test should get in and out of quarantine.

**Review by rmohr — APPROVED** [review]
/lgtm

I don't like it, but it looks ok.

**Pull request merged**
