### PR TITLE
Set check-up-kind-1.19-sriov as voting lane

### PR DESCRIPTION
**Pull request by ormergi**
Following https://github.com/kubevirt/kubevirtci/pull/621 this PR sets check-up-kind-1.19-sriov as voting lane (always run + required)

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/approve
/hold

Feel free to unhold when ready.

**Comment by ormergi** [comment]
> /approve
> /hold
> 
> Feel free to unhold when ready.

Thank you :slightly_smiling_face:

**Pull request merged**
