### PR TITLE
Add Matthew Arnold to kubevirt members.

### PR DESCRIPTION
**Pull request by maya-r**
Matthew has done work on libnbd Go bindings and CDI.

### CODE REVIEW

**Comment by maya-r** [comment]
fyi @mrnold

**Comment by dhiller** [comment]
Hey @mrnold, welcome! 

We have recently created a membership policy, please have a look at the requirements for membership here: https://github.com/kubevirt/community/blob/master/membership_policy.md#requirements

@maya-r I figure you want to be one of the sponsors, right?

**Comment by maya-r** [comment]
Yes. I suppose I'll need another one. Perhaps @fdupont-redhat could be one?
I haven't really said anything to Matthew before submitting this PR.

**Comment by fdupont-redhat** [comment]
I'd be happy to sponsor Matthew.

**Comment by mrnold** [comment]
Thanks!

**Comment by dhiller** [comment]
@mrnold could you please go through the checklist as in this example PR: https://github.com/kubevirt/project-infra/pull/1424

Thanks!

**Comment by mrnold** [comment]
# @mrnold 

## Requirements

[X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[X] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[X] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[X] I am actively contributing to KubeVirt<br>
[X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[X] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[X] I have publicly introduced myself to the community through one of the community communication channels<br>

## Sponsors

* @maya-r 
* @fdupont-redhat 

## List of contributions to the KubeVirt project

### PRs reviewed and/or authored
- [List of pull requests](https://github.com/pulls?q=is%3Apr+author%3Amrnold+kubevirt)

### Issues responded to
- https://github.com/kubevirt/containerized-data-importer/issues/1634

**Review by dhiller — APPROVED** [review]
/approve

Welcome!

**Pull request merged**
