### PR TITLE
Add dasionov as a community member

### PR DESCRIPTION
**Pull request by dasionov**
# GitHub Username
@dasionov

## Requirements

- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
- [x] I am actively contributing to KubeVirt
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
- [x] I have publicly introduced myself to the community through one of the community communication channels
(https://github.com/kubevirt/community#socializing)

## Sponsors

* @enp0s3
* @stu-gott

## List of contributions to the KubeVirt project

* PRs reviewed and/or authored
  - https://github.com/kubevirt/kubevirt/pull/12427
  - https://github.com/kubevirt/kubevirt/pull/12473
  - https://github.com/kubevirt/kubevirt/pull/12573
  - https://github.com/kubevirt/kubevirt/pull/12373
  - https://github.com/kubevirt/kubevirt/pull/12640
  - https://github.com/kubevirt/kubevirt/pull/12690

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
Welcome @dasionov !

**Review by dhiller — APPROVED** [review]
/approve

/hold for others to chime in

**Comment by fossedihelm** [comment]
LGTM
Welcome!

**Comment by dhiller** [comment]
/cc @stu-gott 

> Once your sponsors have responded, your request will be reviewed by KubeVirt project approvers. Any missing information will be requested.

**Comment by dhiller** [comment]
/unhold

@stu-gott I am assuming your consent here from what I heard offline.

**Pull request merged**
