### PR TITLE
prow-deploy: reduce test execution time

### PR DESCRIPTION
**Pull request by fgimenez**
Currently `prow-deploy-test` takes around 35m.

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by fgimenez** [comment]
Ready for review, the main changes are:
* Use image from #908 with precompiled config-bootstrapper and phony
* Use kind instead of kubevirtci for the test cluster

The execution times are reduced from ~35min to ~11min, latest execution https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/859/rehearsal-pull-project-infra-prow-deploy-test/1356136878771802113

/cc @dhiller 
/cc @rmohr

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Comment by fgimenez** [comment]
not sure why these additional jobs were triggered by rehearsal

/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-ceph

**Comment by fgimenez** [comment]
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-upg
/override rehearsal-user-guide-presubmit-build

**Comment by fgimenez** [comment]
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-ember-lvm 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-nfs

**Comment by fgimenez** [comment]
Somehow `pull-project-infra-prow-deploy-test` is stuck running tests from a commit in this PR that makes the tests fail, overriding it to update the job config to the latest successfully tested changes.

/override pull-project-infra-prow-deploy-test

**Pull request merged**
