### PR TITLE
ssp-operator: Archive kubevirt-ssp-operator & kubevirt-template-validator

### PR DESCRIPTION
**Pull request by lyarwood**
These have been unused for some time now and even marked as deprecated within the repo README so lets archive.

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

Thanks @lyarwood !

**Comment by dhiller** [comment]
/approve
/lgtm

/rehearse

Obviously the unmodified job fails due to missing `--allow-repo-archival`, therefore running a rehearsal to check this.

/hold

We can override the original presubmit if the rehearsal succeeds, which I assume.

**Comment by lyarwood** [comment]
> Obviously the unmodified job fails due to missing `--allow-repo-archival`, therefore running a rehearsal to check this.
> 
> We can override the original presubmit if the rehearsal succeeds, which I assume.

Yeah apologies wasn't thinking when I posted this, looks like the rehearsal worked however so I think we can override if you're happy?

**Comment by dhiller** [comment]
> > Obviously the unmodified job fails due to missing `--allow-repo-archival`, therefore running a rehearsal to check this.
> > We can override the original presubmit if the rehearsal succeeds, which I assume.
> 
> Yeah apologies wasn't thinking when I posted this, looks like the rehearsal worked however so I think we can override if you're happy?

Yep, thanks!

/unhold
/override pull-kubevirt-org-github-config-updater

**Pull request merged**
