### PR TITLE
kubevirt,presubmits: set monitoring lane to trigger manually

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

The sig-monitoring lane was bumped to kubernetes 1.29[1] however there are
tests that always fail against this version[2].

Setting the lane to be optional and to be triggered manually

[1] https://github.com/kubevirt/project-infra/pull/3212
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11052/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1750798923670228992

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:
```release-note

```

### CODE REVIEW

**Comment by brianmcarey** [comment]
/cc @dhiller 

The sig-monitoring lane fails consistently on kubernetes versions >1.26 - falling back to 1.26 for now to unblock PRs. 

@machadovilaca @sradco - can you take a look at getting this lane upgraded as 1.26 is no longer a supported version for the kubevirt main branch? 

Some example failures: 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11081/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1750561160903528448
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/10888/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1750556658599202816
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11063/pull-kubevirt-e2e-k8s-1.29-sig-monitoring/1750547862384545792

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
