### PR TITLE
Add avlitman to kubevirt members

### PR DESCRIPTION
**Pull request by avlitman**
# GitHub Username
@avlitman

## Requirements

- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
- [x] I am actively contributing to KubeVirt<br>
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
- [x] I have publicly introduced myself to the community through one of the community communication channels<br>

(https://github.com/kubevirt/community#socializing)

## Sponsors

* @dhiller
* @nunnatsa 

## List of contributions to the KubeVirt project

* PRs reviewed and/or authored
- https://github.com/kubevirt/kubevirt/pull/8774
- https://github.com/kubevirt/kubevirt/pull/9822
- https://github.com/kubevirt/kubevirt/pull/10006
* Issues responded to
- https://github.com/kubevirt/kubevirt/issues/9714
- https://github.com/kubevirt/kubevirt/issues/9836
- https://github.com/kubevirt/containerized-data-importer/issues/2773

**Note to reviewer:**
Member list was ordered alphabetically.

### CODE REVIEW

**Comment by avlitman** [comment]
Hi @dhiller, @nunnatsa I will appreciate your +1 as my sponsors for this PR.

**Review by brianmcarey — COMMENTED** [review]
Hi @avlitman - I believe there is a template that is generally used for these PRs - https://github.com/kubevirt/community/blob/main/membership_checklist.md

Also I am not sure if we want to reorganize usernames starting with uppercase characters - I see they are all grouped towards the top.

**Comment by dhiller** [comment]
> Hi @dhiller, @nunnatsa I will appreciate your +1 as my sponsors for this PR.

Happy to sponsor you here @avlitman

**Comment by avlitman** [comment]
> Hi @avlitman - I believe there is a template that is generally used for these PRs - https://github.com/kubevirt/community/blob/main/membership_checklist.md
> 
> Also I am not sure if we want to reorganize usernames starting with uppercase characters - I see they are all grouped towards the top.

So you prefer order by just a-z?

**Comment by brianmcarey** [comment]
> > Hi @avlitman - I believe there is a template that is generally used for these PRs - https://github.com/kubevirt/community/blob/main/membership_checklist.md
> > Also I am not sure if we want to reorganize usernames starting with uppercase characters - I see they are all grouped towards the top.
> 
> @brianmcarey So you prefer order by just a-z?

I think so. @dhiller what do you think?

**Comment by dhiller** [comment]
> > > Hi @avlitman - I believe there is a template that is generally used for these PRs - https://github.com/kubevirt/community/blob/main/membership_checklist.md
> > > Also I am not sure if we want to reorganize usernames starting with uppercase characters - I see they are all grouped towards the top.
> > 
> > 
> > @brianmcarey So you prefer order by just a-z?
> 
> I think so. @dhiller what do you think?

I agree, case shouldn't matter here.

**Comment by avlitman** [comment]
> > > > Hi @avlitman - I believe there is a template that is generally used for these PRs - https://github.com/kubevirt/community/blob/main/membership_checklist.md
> > > > Also I am not sure if we want to reorganize usernames starting with uppercase characters - I see they are all grouped towards the top.
> > > 
> > > 
> > > @brianmcarey So you prefer order by just a-z?
> > 
> > 
> > I think so. @dhiller what do you think?
> 
> I agree, case shouldn't matter here.

Fixed

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
