### PR TITLE
Update golang version for capk, kubevirt-csi, cloud-provider-kubevirt

### PR DESCRIPTION
**Pull request by davidvossel**

### CODE REVIEW

**Review by brianmcarey — APPROVED** [review]
/approve

/hold

Looks like there is a small issue with the csi linter lane

**Comment by mfranczy** [comment]
@brianmcarey could you rerun the CSI driver lint job? 
/rehearse rehearsal-pull-csi-driver-linter

I have no permissions to do so.

**Comment by brianmcarey** [comment]
> 

I don't think its a permission issue - looks like there is some issue with our rehearse plugin. 

If `make linter` passes against the latest CSI driver locally - I am happy to approve this.

**Comment by brianmcarey** [comment]
Changes have already been applied to the csi-driver presubmits - https://github.com/kubevirt/project-infra/pull/2938 - hence the rehearsals are not being scheduled here. 

Remaining rehearsals all succeeded.

/unhold

**Pull request merged**
