### PR TITLE
Remove rootful kubevirt presubmit lanes

### PR DESCRIPTION
**Pull request by brianmcarey**
It was agreed on the mailing list[1] that the rootful lanes could be removed after the 0.59 release.

This will help reduce the CI load and hopefully lead to reduction in time to merge for approved PRs.

[1] https://groups.google.com/g/kubevirt-dev/c/LC8uSG2NMSA/m/YjkW1GVQHAAJ

/cc @xpivarc @dhiller @EdDev

### CODE REVIEW

**Comment by brianmcarey** [comment]
/hold

to allow for feedback on mailing list

**Review by EdDev — APPROVED** [review]

**Comment by brianmcarey** [comment]
/unhold

thanks everyone!

**Pull request merged**
