### PR TITLE
testing new hosts

### PR DESCRIPTION
**Pull request by rmohr**
/hold

```
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-os-3.11.0-crio  -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-k8s-1.11.0 -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-k8s-genie-1.11.1 -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-k8s-1.13.3 -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-k8s-multus-1.13.3 -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-os-3.11.0-crio -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-os-3.11.0-multus -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-os-3.11.0 -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
mkpj --pull-number 2338 -job pull-packer-kubevirt-e2e-windows2016 -job-config-path github/ci/prow/files/jobs/ --config-path github/ci/prow/files/config.yaml > job.yaml
oc create -f job.yaml -n kubevirt-prow-jobs
```

 * Disable docker cache
 * Schedule on new nodes only

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
Just curious why `packer`?

**Comment by rmohr** [comment]
Should have been `packet`. :dagger:

**Pull request closed without merging**
