### PR TITLE
Set pull-kubevirt-e2e-kind-1.19-sriov as voting lane

### PR DESCRIPTION
**Pull request by ormergi**
Following kubevirt/kubevirtci#621, kubevirt/kubevirt#5906 and kubevirt/kubevirt#5911 this PR sets pull-kubevirt-e2e-kind-1.19-sriov as voting lane (always run + required)

### CODE REVIEW

**Comment by ormergi** [comment]
/hold 

This PR should be merged only after kubevirt/kubevirt#5906 is merged

**Review by fgimenez — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
See https://github.com/kubevirt/kubevirt/pull/5911

**Comment by ormergi** [comment]
> See [kubevirt/kubevirt#5911](https://github.com/kubevirt/kubevirt/pull/5911)

This is merged now we have all the bits on kubevirt

/unhold

**Pull request merged**
