### PR TITLE
sig-network, ipv6: Bump provider to 1.24

### PR DESCRIPTION
**Pull request by oshoval**
Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2149/rehearsal-pull-kubevirt-e2e-k8s-1.24-ipv6-sig-network/1536327535296516096
passed (once kubevirtci bump done on kubevirt)

**Review by maiqueb — APPROVED** [review]
Now this is staying ahead of the game ...

Thanks.

**Review by brianmcarey — COMMENTED** [review]
lgtm

**Review by maiqueb — APPROVED** [review]

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
