### PR TITLE
Bump flakefinder to the latest version with anchors

### PR DESCRIPTION
**Pull request by rmohr**
In order to point people to specific lines in the reports, add anchors to every line.
anchors

Further back-links will now ease the navigation between the generated tables.

### CODE REVIEW

**Comment by rmohr** [comment]
@dhiller I think that the flakefinder jobs belong to project-infra. Something we should change.

**Comment by dhiller** [comment]
> @dhiller I think that the flakefinder jobs belong to project-infra. Something we should change.

not sure of that, as it's information for the analyzed project? Or is that meant rather in terms of who controls this>

**Pull request merged**
