### PR TITLE
Bump containerdisks repo to golang 1.17

### PR DESCRIPTION
**Pull request by 0xFelix**
Needed for https://github.com/kubevirt/containerdisks/pull/18

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by brianmcarey** [comment]
@0xFelix pull-project-infra-check-testgrid-config is failing across all PRs at the moment and is set as optional. It is not related to your change and once you get the approved label it should be good to merge.

**Comment by 0xFelix** [comment]
@rmohr Can you approve?

**Pull request merged**
