### PR TITLE
Move bootstrap from docker io to quay.io

### PR DESCRIPTION
**Pull request by oshoval**
This commit update specific bootstrap from
docker.io to quay.io (and also updates the version).

from kubevirtci/bootstrap:v20201119-a5880e0
to quay.io/kubevirtci/bootstrap:v20210311-09ebaa2

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
Can i rehearse ? 
it will run lots of jobs at the same time but..

**Comment by fgimenez** [comment]
> Can i rehearse ?

Not the best moment for sure. Let's wait until the merge queue is empty and we are on low load (outside of office hours).

**Comment by oshoval** [comment]
> > Can i rehearse ?
> 
> Not the best moment for sure. Let's wait until the merge queue is empty and we are on low load (outside of office hours).

Maybe lets do it even safer ?
lets push the images that are on docker.io to quay.io and just use the same ones but point to quay?
if you are good with it, i will create a list of images
for example the one i used here `kubevirtci/bootstrap:v20201119-a5880e0`

**Comment by fgimenez** [comment]
No, the problem is triggering more than 150 jobs simultaneously, changing to the new image should be ok (and if we get errors they should be fixed easily).

**Comment by oshoval** [comment]
As we spoke, created a sanity of 14 jobs 
https://github.com/kubevirt/project-infra/pull/1042

**Comment by oshoval** [comment]
As this PR is too big to rehearsal, i am closing it and open smaller ones

**Pull request closed without merging**
