### PR TITLE
presubmit, kubevirtci, vgpu: Bump to 1.27

### PR DESCRIPTION
**Pull request by oshoval**
Depends on https://github.com/kubevirt/kubevirtci/pull/1026

### CODE REVIEW

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2822/rehearsal-check-up-kind-1.27-vgpu/1668255102374252544

Passed, removing the hack

**Comment by oshoval** [comment]
/hold cancel

@brianmcarey @dhiller can you please take a look ?

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
