### PR TITLE
infra, presubmit, Update build jobs to use quay.io

### PR DESCRIPTION
**Pull request by oshoval**
In order to fix docker.io rate limit,
update builder jobs to use quay.io instead.

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
the rehearsal passed,
since its use -b it doesnt publish the images

**Review by fgimenez — APPROVED** [review]
/lgtm
/approve

**Comment by oshoval** [comment]
Thanks Federico

**Pull request merged**
