### PR TITLE
Make pull-kubevirt-build required

### PR DESCRIPTION
**Pull request by rmohr**
It is important to see this job, in order to see if `make` detected
uncommited code-changes, similare to the generate job.

Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

@danielBelenky it seems like this job does not check for diffs, can that be?

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Comment by rmohr** [comment]
> /hold
> 
> @danielBelenky it seems like this job does not check for diffs, can that be?

/hold cancel

False alarm we are covered on master.

**Pull request merged**
