### PR TITLE
Migrate ovs-cni repository under network plumbing working group organization

### PR DESCRIPTION
**Pull request by phoracek**
As agreed on Network Plumbing Working Group call [1], OVS CNI will be moved under the working group GitHub organization. This CNI is not specific to virtualization and in fact was adopted by users that do not run KubeVirt on their setups. Thus, moving this under this shared and network-specific organization.

[1] https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit#heading=h.y7bd8z7vnd4h

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/approve
/hold

Hold until tests are done. Will merge this together with the repo transfer.

**Comment by fgimenez** [comment]
/override pull-project-infra-check-testgrid-config

I need to fix this one, feel free to ignore.

**Pull request merged**
