### PR TITLE
Add chandramerla as kubevirt org member

### PR DESCRIPTION
**Pull request by chandramerla**
# GitHub Username
@chandramerla 

## Requirements

[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[x] I am actively contributing to KubeVirt<br>
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[x] I have publicly introduced myself to the community through one of the community communication channels<br>

(https://github.com/kubevirt/community#socializing)

## Sponsors

* @brianmcarey 
* @dhiller 

## List of contributions to the KubeVirt project

**PRs reviewed and/or authored**
 - on kubevirt/project-infra - https://github.com/kubevirt/project-infra/pulls?q=is%3Apr+is%3Aclosed+author%3Achandramerla
 - on kubevirt/kubevirtci - https://github.com/kubevirt/kubevirtci/pulls?q=is%3Apr+is%3Aclosed+author%3Achandramerla

**Issues responded to**
- https://github.com/kubevirt/kubevirt/pull/12978#issuecomment-2393558683

> [!IMPORTANT]
> After this pull request has been merged, an invitation to the KubeVirt GitHub organization will be automatically sent to the new member. The new member needs to accept the invitation to receive member status.

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
Hi @chandramerla  - it will be good to have you as part of the org. 

Can you update this so that you are added in alphabetical order?

**Comment by chandramerla** [comment]
> Hi @chandramerla - it will be good to have you as part of the org.
> 
> Can you update this so that you are added in alphabetical order?

Thanks, Brian. I've reordered names in the the current list to be sorted alphabetically

**Review by dhiller — APPROVED** [review]
Hey @chandramerla , great to have you here! :partying_face: 

Welcome to the KubeVirt community! :tada:

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by chandramerla** [comment]
> /hold for two days so to give others the chance to chime in.

Since two days have passed, can one of you remove the hold label? Thanks!

**Pull request merged**
