### PR TITLE
build: Dependabot bumps &  fixes

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

- bump golang.org/x/image from 0.5.0 to 0.18.0
- bump google.golang.org/grpc from 1.54.0 to 1.56.3
- bump github.com/hashicorp/go-retryablehttp from 0.6.6 to 0.7.7
- bump google.golang.org/protobuf from 1.30.0 to 1.33.0
- bump github.com/go-git/go-git/v5 from 5.3.0 to 5.11.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3726 #3728  #3729  #3730 #3731 #3732 #3735

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by brianmcarey** [comment]
/override pull-project-infra-grafana-deploy-test

See https://github.com/kubevirt/project-infra/pull/3746

**Review by dhiller — APPROVED** [review]
/approve

Thank you @brianmcarey !

**Pull request merged**
