### PR TITLE
Bump go version of KubeVirt CCM jobs to 1.20

### PR DESCRIPTION
**Pull request by mfranczy**
Bump go version of KubeVirt CCM jobs to 1.20

### CODE REVIEW

**Comment by mfranczy** [comment]
cc @davidvossel

**Comment by gonzolino** [comment]
@mfranczy I think CCM is still using go 1.19. Do we need to update it in parallel to this change?

**Comment by mfranczy** [comment]
@gonzolino right. I forgot to push the PR.

**Comment by mfranczy** [comment]
The PR https://github.com/kubevirt/cloud-provider-kubevirt/pull/250

**Comment by mfranczy** [comment]
However, this PR has to be merged before the bump in the CCM repo.

**Comment by gonzolino** [comment]
great :)
leaving the approval for @rmohr or @davidvossel , since I am not really familiar with prow.

/lgtm

**Comment by mfranczy** [comment]
@qinqon could you take a look as well?

**Comment by mfranczy** [comment]
closing in favor of https://github.com/kubevirt/project-infra/pull/2892

**Pull request closed without merging**
