### PR TITLE
Bump kubevirtci on controller-lifecycle-operator-sdk-e2e

### PR DESCRIPTION
**Pull request by akalenyu**
Current kubevirtci is ancient (pulls from dockerhub!) 
Verified locally

### CODE REVIEW

**Comment by brianmcarey** [comment]
@akalenyu does the kubevirtci commit ref need to be updated? 

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2668/rehearsal-pull-controller-lifecycle-operator-sdk-e2e-k8s-1.24/1637781398867677184#1:build-log.txt%3A25

**Comment by akalenyu** [comment]
> @akalenyu does the kubevirtci commit ref need to be updated?
> 
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2668/rehearsal-pull-controller-lifecycle-operator-sdk-e2e-k8s-1.24/1637781398867677184#1:build-log.txt%3A25

Yep, working on this in https://github.com/kubevirt/controller-lifecycle-operator-sdk/pull/23/commits/ded21131a67048aa9453b14319072ac12734d68b

**Review by brianmcarey — APPROVED** [review]
/lgtm

/approve

**Comment by brianmcarey** [comment]
/override rehearsal-pull-controller-lifecycle-operator-sdk-e2e-k8s-1.24

**Pull request merged**
