### PR TITLE
Adapt to ginkgo 2.0 params

### PR DESCRIPTION
**Pull request by oshoval**
Update deprecated argument from `--noColor` to `--no-color`

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
Thanks Quique

**Comment by oshoval** [comment]
failure not related to the PR

**Review by enp0s3 — APPROVED** [review]
/approve

**Comment by oshoval** [comment]
Thanks Igor

/retest

**Pull request merged**
