### PR TITLE
infra, Remove docker.io preset from kubernetes-crud-ci-role

### PR DESCRIPTION
**Pull request by oshoval**
In case we don't need it, lets remove it.

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
This job fails even out of the box

**Comment by oshoval** [comment]
/cc @fgimenez FYI

https://github.com/kubevirt/project-infra/pull/1089#issuecomment-806503652

**Comment by oshoval** [comment]
@fgimenez
as we spoke, removed the preset, the job fails but not due to that.
PR ready to review, thanks

**Review by fgimenez — APPROVED** [review]
/lgtm
/approve

The rehearse problem is not related to these changes :+1:

**Comment by oshoval** [comment]
@fgimenez can you take a look please why this one is not merged?
the failing job is not "Required", and its also a rehearsal

maybe since i ran it, it blocks it ? so i need to rebase or something if so ?
thanks

**Comment by oshoval** [comment]
Rebased, PTAL

**Pull request merged**
