### PR TITLE
Require compute and operator for non-root

### PR DESCRIPTION
**Pull request by xpivarc**
Signed-off-by: L. Pivarc <lpivarc@redhat.com>

### CODE REVIEW

**Comment by xpivarc** [comment]
Depends on https://github.com/kubevirt/kubevirt/pull/4922

**Comment by xpivarc** [comment]
Depends on https://github.com/kubevirt/kubevirt/pull/6041

**Comment by xpivarc** [comment]
/cc @rmohr @fgimenez 
The nonroot got merged. Please have a look.

**Comment by rmohr** [comment]
/lgtm
/approve

@fgimenez let's keep an eye on this if we can handle this in CI.

**Pull request merged**
