### PR TITLE
Move CDI e2e lanes to the new workloads cluster

### PR DESCRIPTION
**Pull request by brianmcarey**
/cc @dhiller @awels

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve

Unfortunately we can not rehearse here :(

**Comment by brianmcarey** [comment]
@awels - the old cluster has been reduced to two nodes so CDI would probably get better service on the new cluster. The rehearsal of one of the e2e jobs looks good. 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2735/rehearsal-pull-containerized-data-importer-e2e-ceph/1653698562212499456

**Comment by awels** [comment]
Nice
/lgtm

**Pull request merged**
