### PR TITLE
kubevirt e2e Arm64: using kind-1.27 cluster to run e2e test on Arm64

### PR DESCRIPTION
**Pull request by zhlhahaha**
Hold until https://github.com/kubevirt/kubevirtci/pull/1027 get merged.

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by zhlhahaha** [comment]
@brianmcarey  Where can I see the rehearsal test result?

**Comment by brianmcarey** [comment]
@zhlhahaha I think we still need to wait for the following PR to merge: 
https://github.com/kubevirt/kubevirt/pull/9924

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2826/rehearsal-pull-kubevirt-e2e-arm64/1669615955489067008

**Review by brianmcarey — APPROVED** [review]
/approve

/unhold 

Rehearsal looks good - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2826/rehearsal-pull-kubevirt-e2e-arm64/1670127618348814336

**Pull request merged**
