### PR TITLE
Manage operator tests using its dedicated SIG label

### PR DESCRIPTION
**Pull request by enp0s3**
Instead of filtering based on the `Operator` string now we can use `[sig-operator]` instead.

Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

### CODE REVIEW

**Comment by enp0s3** [comment]
/hold

Lets wait till #[5534](https://github.com/kubevirt/kubevirt/pull/5534) will be merged

/cc @fgimenez

**Review by fgimenez — APPROVED** [review]
/lgtm
/approve
/hold

Nice, thanks! Feel free to unhold when https://github.com/kubevirt/kubevirt/pull/5534 is in.

**Comment by fgimenez** [comment]
Something is wrong with the yamls though, we need to have tests passing before merging this one.

**Review by fgimenez — APPROVED** [review]
/lgtm

Great all looking good now, we can unhold when kubevirt/kubevirt#5534 is merged.

**Comment by fgimenez** [comment]
/unhold

https://github.com/kubevirt/kubevirt/pull/5534 is merged

**Pull request merged**
