### PR TITLE
chore: enable branch protection for kubevirt-tekton-tasks

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
chore: enable branch protection for kubevirt-tekton-tasks

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by dhiller** [comment]
@ksimon1 I overlooked that if you enable tide you also need to enable lgtm and approve plugins. 

I'll fetch an example PR later and attach it to this PR. 

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3513/check-prow-config/1810283836047626240

**Comment by dhiller** [comment]
> @ksimon1 I overlooked that if you enable tide you also need to enable lgtm and approve plugins.
> 
> I'll fetch an example PR later and attach it to this PR.
> 
> [prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3513/check-prow-config/1810283836047626240](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3513/check-prow-config/1810283836047626240)

Here's the docs about merge automation: https://github.com/kubevirt/community/blob/main/docs/add-merge-automation-to-your-repository.md
Here's an example PR: https://github.com/kubevirt/project-infra/pull/653/files

**Comment by ksimon1** [comment]
@dhiller can you please check this PR again?

**Review by dhiller — APPROVED** [review]
Looks good to me @ksimon1 , thank you!

**Pull request merged**
