### PR TITLE
Make 1.26 PSA network lane gating

### PR DESCRIPTION
**Pull request by acardace**
Signed-off-by: Antonio Cardace <acardace@redhat.com>

### CODE REVIEW

**Comment by acardace** [comment]
Depends on https://github.com/kubevirt/kubevirt/pull/9112

**Comment by xpivarc** [comment]
/lgtm
/hold
Waiting for https://github.com/kubevirt/kubevirt/pull/9112

@brianmcarey @dhiller Can you have a look?

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
