### PR TITLE
Add Nithish Karthik as a Community Member

### PR DESCRIPTION
**Pull request by sudo-NithishKarthik**
# GitHub Username
@sudo-NithishKarthik

## Requirements
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
[x] I am actively contributing to KubeVirt<br>
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
[x] I have publicly introduced myself to the community through one of the community communication channels<br>
(https://github.com/kubevirt/community#socializing)

## Sponsors
* @alicefr
* @xpivarc

## List of contributions to the KubeVirt project
* PRs reviewed and/or authored
- [[Refactor] Use ambient capabilities for the virt-launcher binary](https://github.com/kubevirt/kubevirt/pull/9599)
- [[Refactor] Validate evictionStrategy in KubeVirt Config Update](https://github.com/kubevirt/kubevirt/pull/9489)
- [[[Fix] Get rid of noisy logs in checkVolumesForMigration ]](https://github.com/kubevirt/kubevirt/pull/9455)
- [[Fix] Avoid nil pointer dereferencing when trying to access
  evictionStrategy](https://github.com/kubevirt/kubevirt/pull/9454)
- [[Docs] Update Docs for Docker Authentication in Mac](https://github.com/kubevirt/kubevirt/pull/9344)
- Author of repository for generating seccomp profile at runtime (repository: https://github.com/kubevirt/project-infra/pull/2923)
* Issues responded to
- [[GSoc] Create KubeVirt seccomp profiles](https://github.com/kubevirt/community/issues/205)
- [virt-launcher: leverage ambient capabilities](https://github.com/kubevirt/kubevirt/issues/8967)

### CODE REVIEW

**Comment by alicefr** [comment]
Put hold to allow other to review this
/cc @aburdenthehand @dhiller @xpivarc

**Comment by alicefr** [comment]
@sudo-NithishKarthik is participating in the [GSoc program](https://github.com/kubevirt/community/issues/205) for generating the seccomp profile at runtime, he meets regularly with @xpivarc and I and his work will be published under https://github.com/kubevirt/k8s-seccomp-generator

**Review by dhiller — APPROVED** [review]
/approve

**Review by xpivarc — APPROVED** [review]

**Pull request merged**
