### PR TITLE
Give iholder101 permission to add labels to issues

### PR DESCRIPTION
**Pull request by iholder101**

### CODE REVIEW

**Review by enp0s3 — APPROVED** [review]
/approve

**Comment by xpivarc** [comment]
/hold
This seems a little bit weird to me. Only maintainers are in this group and the PR is approved by someone who is not in the group.
Why do you require this? Can you ask one of the members of the group to approve this PR?

**Comment by xpivarc** [comment]
> > /hold This seems a little bit weird to me. Only maintainers are in this group and the PR is approved by someone who is not in the group. Why do you require this? Can you ask one of the members of the group to approve this PR?
> 
> Is adding labels to issues dangerous enough that we need to be so careful around it? TBH, I'm not even sure why we can't allow all reviewers to do so.

Labels and restricted labels are two distinct things. I can't speak about the intentions of somebody else(in this case the person who set this up in this way) but I would seek clarification or their approval if anything.

I guess the motivation for your change is https://github.com/kubevirt/kubevirt/issues/10120#issuecomment-1637634143 which seems to me like miss-configuration.
fyi @dhiller

**Comment by enp0s3** [comment]
@xpivarc @iholder101 Hi! the aim of this change is to give permission for a member to add `good-first-issue` label to issues. This wasn't about giving permission to every restricted label

**Comment by enp0s3** [comment]
@xpivarc @dhiller My apologies. Are there any other labels which may cause privilege escalation?

**Comment by dhiller** [comment]
Before the setup for enabling `good-first-issue` to be set was done through 
https://github.com/kubevirt/project-infra/commit/13b4c7e0a5f9c2df79ba08c483b08c784b3f2ce0 and https://github.com/kubevirt/project-infra/commit/13b4c7e0a5f9c2df79ba08c483b08c784b3f2ce0 we couldn't even set the label via `label` plugin. I don't remember the exact content of the discussion around it, but IIRC we agreed that a limited number of persons to set the label would be good enough. @aburdenthehand do you remember?

**Comment by dhiller** [comment]
Now I remember that we agreed to leave it to the [maintainers](https://github.com/kubevirt/community/blob/main/MAINTAINERS.md) of the project to add this label for every repo, which the `kubevirt-label` group targets.

It would be possible to add @iholder101 to the `kubevirtkubevirt-label` group, though. Maybe that would be enough already?

**Comment by iholder101** [comment]
> It would be possible to add @iholder101 to the `kubevirtkubevirt-label` group, though. Maybe that would be enough already?

Sure, that works for me. :+1: 

Do we want to consider permitting certain organization members to add new labels? Perhaps reviewers/approvers?

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
