### PR TITLE
Add new lane for the 'Operator' test

### PR DESCRIPTION
**Pull request by nunnatsa**
Use the new KV test feature to pass the `KUBEVIRT_E2E_FOCUS` and the `KUBEVIRT_E2E_SKIP` variables in order to create a new lane for the KV operator test as an isolated test.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Comment by nunnatsa** [comment]
Fixed typo

**Comment by rmohr** [comment]
/lgtm
/approve

Just to explicitly spell it out: With this change we are testing less on PRs. We only test the operator now on 1.19 on PRs. Our periodics will still test it on all versions. We can revert this change, when some migration and operator fixes landed.

**Review by fgimenez — COMMENTED** [review]
/lgtm

**Comment by rmohr** [comment]
Checked the executed and skipped tests. Looks correct.

**Pull request merged**
