### PR TITLE
Add configurations for HCO release-1.2 branch

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

**Review by tiraboschi — APPROVED** [review]

**Comment by nunnatsa** [comment]
@jean-edouard - what should be done in order to merge it?

**Comment by jean-edouard** [comment]
@nunnatsa sorry I didn't notice this PR already had an LGTM, that should do it:
/approve

**Pull request merged**
