### PR TITLE
cnao, increase max_concurrency to 11

### PR DESCRIPTION
**Pull request by RamLavi**
Increased max_concurrency in all relevant
CNAO presubmits jobs

Signed-off-by: Ram Lavi <ralavi@redhat.com>

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold
until #582 gets approved so I could change  it there as well

**Comment by RamLavi** [comment]
/hold cancel

#582 merged

**Comment by phoracek** [comment]
I recall that setting the amount of concurrent jobs was a balancing act affecting all the lanes.

@rmohr would you know?

**Comment by rmohr** [comment]
How much traffic do you have, that you really need 11 concurrent PR runs?

**Comment by RamLavi** [comment]
> How much traffic do you have, that you really need 11 concurrent PR runs?

we recently added tier1 lanes to the CNAO repo, so each PR will run cnao e2e tests(=2), and a tier1 test for each component(=6), so it sums up to 8 per PR.
granted most of them are small tier1 tests, but allowing running them in parallel will help IMO.

But I leave it to your judgment :)

**Comment by rmohr** [comment]
> we recently added tier1 lanes to the CNAO repo, so each PR will run cnao e2e tests(=2), and a tier1 test for each component(=6), so it sums up to 8 per PR.

There may be a misunderstanding. The max_concurrency limit is per job. If you define 6 jobs for a repo with a limit of 6, you can run on 6 PRs in parallel all jobs (total of 36 jobs).

**Comment by RamLavi** [comment]
> > we recently added tier1 lanes to the CNAO repo, so each PR will run cnao e2e tests(=2), and a tier1 test for each component(=6), so it sums up to 8 per PR.
> 
> There may be a misunderstanding. The max_concurrency limit is per job. If you define 6 jobs for a repo with a limit of 6, you can run on 6 PRs in parallel all jobs (total of 36 jobs).

I indeed misunderstood. Thanks @rmohr @phoracek :) ! closing PR

**Pull request closed without merging**
