### PR TITLE
Virt Blocks: Use newer container image

### PR DESCRIPTION
**Pull request by andreabolognani**
Hopefully the last change needed for a while :)

### CODE REVIEW

**Comment by andreabolognani** [comment]
As per bot's request,

/assign @cynepco3hahue

I clearly haven't quite wrapped my head around the expected workflow yet :/

**Comment by slintes** [comment]
@andreabolognani to be honest, I don't understand why your approval didn't work, can you try again please? Trying to debug this. 
And prow is always suggesting other apporovers in case there is an approval needed, does not need to be the same person as suggested.

**Comment by slintes** [comment]
oh, and in case this is urgent, let me know, will approve myself then

**Comment by andreabolognani** [comment]
> @andreabolognani to be honest, I don't understand why your approval didn't work, can you try again please? Trying to debug this.

Sure thing:

/approve

> And prow is always suggesting other apporovers in case there is an approval needed, does not need to be the same person as suggested.

Got it!

**Comment by slintes** [comment]
Seems it does not take the additional OWNERS file for the virtblocks config into account for some reason. Investigating...

**Comment by slintes** [comment]
@andreabolognani ok, I tried something (yaml formatting is hard...), can try again please?

**Comment by andreabolognani** [comment]
Sure thing:

/approve

Though looking at the YAML it seems fine to me?

**Comment by andreabolognani** [comment]
Just a hunch: looking at the existing `OWNERS` files, I see

```
./github/ci/prow/files/jobs/kubevirt.github.io/OWNERS
./github/ci/prow/files/jobs/kubevirt-tutorial/OWNERS
./github/ci/prow/files/jobs/virtblocks/virtblocks/OWNERS
```

Is it possible that the machinery is somehow expecting the path `/github/ci/prow/files/jobs/$something/OWNERS` to map to the repository at `github.com/kubevirt/$something`, and is now working because that assumption is broken for Virt Blocks?

Alternatively: `github/ci/prow/files/plugins.yaml` contains

```
triggers:
- repos:
  - kubevirt/project-infra
  ...
  - kubevirt/kubevirt-tutorial
  trusted_org: kubevirt
- repos:
  - virtblocks/virtblocks

approve:
- repos:
  - kubevirt/project-infra
  ...
  - kubevirt/kubevirt
  require_self_approval: true
  lgtm_acts_as_approve: false
  ignore_review_state: true
```

with `virtblocks/virtblocks` being present in the `triggers` section but conspicuously absent from the `approve` section...

All of the above is pure speculation made with basically no knowledge of the platform, so I expect it to be partially or completely off-base.

**Comment by slintes** [comment]
I see it still didn't work, will apporve myself for this one.

> Is it possible that the machinery is somehow expecting the path /github/ci/prow/files/jobs/$something/OWNERS

to my best knowledge no. The deal ist just that an OWNERS file is for the directory where it lives and all subdirectories.

> with virtblocks/virtblocks being present in the triggers section but conspicuously absent from the approve section...

this is about PRs in the virtblocks repo itself

/approve

**Comment by andreabolognani** [comment]
> > Is it possible that the machinery is somehow expecting the path /github/ci/prow/files/jobs/$something/OWNERS
> 
> to my best knowledge no. The deal ist just that an OWNERS file is for the directory where it lives and all subdirectories.
> 
> > with virtblocks/virtblocks being present in the triggers section but conspicuously absent from the approve section...
> 
> this is about PRs in the virtblocks repo itself

I see! As I said, both were sort of shots in the dark based on poking around for a few minutes with no real knowledge of the infrastructure.

> I see it still didn't work, will apporve myself for this one.
> 
> /approve

Thanks a lot!

**Pull request merged**
