### PR TITLE
Add RoniKishner to kubevirt members list

### PR DESCRIPTION
**Pull request by RoniKishner**
# GitHub Username
RoniKishner

## Requirements

- [X] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
- [X]  I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
- [X]  I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
- [X]  I am actively contributing to KubeVirt<br>
- [X]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
- [X] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
- [X]  I have publicly introduced myself to the community through one of the community communication channels<br>

(https://github.com/kubevirt/community#socializing)

## Sponsors

* @0xFelix 
* @lyarwood 

## List of contributions to the KubeVirt project

- https://github.com/kubevirt/kubevirt/pull/11448
- https://github.com/kubevirt/kubevirt/pull/10334

### CODE REVIEW

**Comment by 0xFelix** [comment]
Welcome Roni!

/lgtm
/test all

**Comment by enp0s3** [comment]
@RoniKishner Welcome!

/approve

**Pull request merged**
