### PR TITLE
Update to GitHub website and user-guide repos

### PR DESCRIPTION
**Pull request by cwilkers**
Changes suggested in kubevirt-dev mailing list by @mazzystr 

Signed-off-by: cwilkers <cwilkers@redhat.com>

### CODE REVIEW

**Review by dhiller — CHANGES_REQUESTED** [review]
As I said in the mail to kubevirt-dev, I don't think `admin` access is necessary. Please convince me otherwise.

**Comment by dhiller** [comment]
> I think the history here is Matt Carlton and Adam J built the initial Jekyll website and whatever user-guide was before docsify then created this group to administrate the two repos.
> 
> I say we add all the community repos and change the group name to community-team
> 
> @dhiller sound reasonable?

Sounds reasonable to me.

**Comment by cwilkers** [comment]
I think I accidentally merged instead of rebase, something got crossed here, let's switch to WIP until I can figure it out.

**Comment by cwilkers** [comment]
> I think I accidentally merged instead of rebase, something got crossed here, let's switch to WIP until I can figure it out.

Resolved, looks like the github UI itself was holding on to the old state for comparison, and I had to fully refresh after rebasing.

**Review by dhiller — APPROVED** [review]
/approve

/hold

for others to take a final look, just remove the hold when you feel it's convenient.

Thanks!

**Pull request merged**
