### PR TITLE
rehearse: fix tests and build

### PR DESCRIPTION
**Pull request by fgimenez**
Continued from #845

Most relevant changes:
* Switched from vendor to bazel WORKSPACE-based dependency management for golang subprojects in project-infra following this suggestion https://github.com/kubevirt/project-infra/pull/845#discussion_r575225360 Removed vendor dir and updated all the BUILD files with gazelle.
* Fixed rehearse tests: two git-related changes were required (change merge type from rebase to squash and set git config for running on CI).
* Updated rehearse test prow job: given that the tests are run with bazel we no longer need a golang image, switched to bootstrap, successful execution here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/982/pull-project-infra-test-rehearse/1367445333738524672

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve
/hold

holding for others to review, unhold whenever it makes sense

**Review by dhiller — APPROVED** [review]

**Comment by rmohr** [comment]
I think we still use a very old `.bazelversion` and it seems like some vendor dependencies are still in the repo. Maybe something to address in another PR.

**Pull request merged**
