### PR TITLE
Bump kubevirtci jobs to quay.io/kubevirtci/golang

### PR DESCRIPTION
**Pull request by rmohr**
Switch from kubekins to our own bootstrap images based on fedora with
golang.

### CODE REVIEW

**Comment by rmohr** [comment]
Successful run for sriov: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/554/check-up-kind-1.17-sriov/1371802754099449856
Successful run for another generic provision job:  https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/554/check-provision-k8s-1.17/1371814330735005696

**Comment by rmohr** [comment]
/cc @fgimenez 
/cc @qinqon 

@fgimenez for a general ack, @qinqon for the sriov change.

**Comment by fgimenez** [comment]
ups sorry didn't meant to add lgtm label too

**Pull request merged**
