### PR TITLE
Execute prow-deploy-test in phx-prow

### PR DESCRIPTION
**Pull request by fgimenez**
The test started failing after set to execute on `prow-workloads`, moving it back to `phx-prow` to unblock PRs while investigating the root cause. Also reduced the requested memory, leftover from when the test used kubevirtci. 

/cc @dhiller 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by fgimenez** [comment]
Job with these changes passed here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1338/rehearsal-pull-project-infra-prow-deploy-test/1405501593951932416

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
@fgimenez sorry for reacting so late, I just cleaned up my GitHub notifications (i.e. marked them all as read) so I missed the mention. :confused:

**Comment by fgimenez** [comment]
/override pull-project-infra-prow-deploy-test

np at all :) it happens to me constantly too

**Pull request merged**
