### PR TITLE
Update base image common templates jobs

### PR DESCRIPTION
**Pull request by ksimon1**
Update base image common templates jobs

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
@ksimon1 to make your life a bit easier, there's a script that you can use to update image to latest version in a job definition. Example:

```
./hack/update-jobs-with-latest-image.sh quay.io/kubevirtci/kubevirt-infra-bootstrap github/ci/prow-deploy/files/jobs/kubevirt/common-templates
```

**Comment by ksimon1** [comment]
@dhiller have you ever seen this error?

**Comment by dhiller** [comment]
Prow deploy failed as docker mirror didn't come up. Unrelated, thus

/override pull-project-infra-prow-deploy-test

**Pull request merged**
