### PR TITLE
kubevirtci, SR-IOV: Bump kind version and enable it 

### PR DESCRIPTION
**Pull request by oshoval**
Depends on https://github.com/kubevirt/kubevirtci/pull/1008

### CODE REVIEW

**Comment by oshoval** [comment]
1.27 sriov passed, but we need to test it with kubevirt as well because only there the cpu manager tests that had the problem are failing, (and mirror the image)

**Comment by oshoval** [comment]
/hold

Depends on https://github.com/kubevirt/kubevirtci/pull/1008

**Review by brianmcarey — APPROVED** [review]
/approve

**Comment by oshoval** [comment]
/hold cancel

Thanks

**Pull request merged**
