### PR TITLE
Changes to build bootstrap image for s390x

### PR DESCRIPTION
**Pull request by ibm-jitendra**
Created a separate directory to have changes to build bootstrap image for s390x.

### CODE REVIEW

**Comment by ibm-jitendra** [comment]
@brianmcarey 

Bazel version 5.4.1 encounters compatibility issues on s390x architecture. Here are alternative approaches to construct the bootstrap image:

1. Compile the Bazel binary (version 5.4.1) on the host system and incorporate the binary during the Docker image creation for the bootstrap. This method has been tested and verified as functional.

2. Modify the Dockerfile for the bootstrap by replacing the Fedora39 distribution with Debian Bullseye. Using Debian Bullseye allows successful building and functioning of Bazel 5.4.1.

3. Consider utilizing Bazel version 7.0.x, but since KubeVirt specifically requires Bazel 5.4.1, adjustments need to be made to accommodate the version discrepancy for KubeVirt.

**Comment by ibm-jitendra** [comment]
As discussed with @brianmcarey We are building bootstrap image without Bazel.
Will publish the changes here after verifying.

**Comment by ibm-jitendra** [comment]
@brianmcarey 

Changes for builder images are getting tracked here: https://github.com/kubevirt/kubevirt/pull/11097.
Once we are good to close builder image PR we can review this as well ?

**Review by brianmcarey — COMMENTED** [review]
Thank @ibm-jitendra  - a s390x bootstrap image was added as part of https://github.com/kubevirt/project-infra/pull/3197 so I think we are good to close this PR for now. 

/close

**Pull request closed without merging**
