### PR TITLE
cnao, Add components tier1 functests

### PR DESCRIPTION
**Pull request by RamLavi**
This PR adds tier1 test lanes of the following components in CNAO: multus, bridge-marker, nmstate

### CODE REVIEW

**Comment by RamLavi** [comment]
/hold

until [CNAO PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/504) is merged

**Comment by RamLavi** [comment]
/hold cancel

we can start running this tier1 test.

**Comment by RamLavi** [comment]
/rehearse

checking multiple jobs rehearse

**Review by qinqon — CHANGES_REQUESTED** [review]
I think we are missing github-report flag

**Comment by RamLavi** [comment]
>I think we are missing github-report flag

@qinqon [Done](https://github.com/kubevirt/project-infra/compare/7ff99db1c72946da267e7c73cac9d39a719a66ce..87e881199746a565093974a08bd940a9e5552ca8)

/rehearse

**Pull request merged**
