### PR TITLE
Add nirdothan to KubeVirt Members

### PR DESCRIPTION
**Pull request by nirdothan**
# GitHub Username: @nirdothan

## Requirements

- [x] I have reviewed the [community code of conduct](https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
- [x] I have enabled 2FA on my [GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [kubevirt-dev e-mail list](https://groups.google.com/forum/#!forum/kubevirt-dev)
- [x] I am actively contributing to KubeVirt
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
- [x] I have publicly introduced myself to the community through one of the [community communication channels](https://github.com/kubevirt/community#socializing)

## Sponsors

* @EdDev 
* @orelmisan 

## List of contributions to the KubeVirt project

* PRs reviewed and/or authored
- https://github.com/kubevirt/kubevirt/pull/12959
- https://github.com/kubevirt/kubevirt/pull/12936
- https://github.com/kubevirt/kubevirt/pull/12923
- https://github.com/kubevirt/kubevirt/pull/12921
- https://github.com/kubevirt/kubevirt/pull/12859

### CODE REVIEW

**Comment by enp0s3** [comment]
@nirdothan Welcome aboard!
/ok-to-test
/approve

**Review by EdDev — APPROVED** [review]
Welcome to the Kubevirt organization @nirdothan .

Thank you for the contributions so far and I am looking forward to see more coming.

**Comment by EdDev** [comment]
@orelmisan , waiting for you to ack this as well. Please unhold after.

/hold

**Review by orelmisan — APPROVED** [review]
Welcome @nirdothan!
/hold cancel

**Pull request merged**
