### PR TITLE
Replace inline pgp-bot-key volumes with a preset

### PR DESCRIPTION
**Pull request by rabin-io**
Adding the pgp-bot-key preset for prowjobs

Issue #2449

Signed-off-by: Rabin Yasharzadehe <rabin@redhat.com>

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
/lgtm 

Thanks @rabin-io 

/cc @dhiller

**Review by dhiller — COMMENTED** [review]
Nice spot @rabin-io , thank you!

/approve

**Comment by rabin-io** [comment]
> Nice spot @rabin-io , thank you!

And thank you, @brianmcarey as well for all the guidance.

**Pull request merged**
