### PR TITLE
 release-tool: allow beta tags without --force

### PR DESCRIPTION
**Pull request by acardace**
adds new release configs

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
Seems good to me, @davidvossel PTAL

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
Sorry, didn't see the other request

**Comment by xpivarc** [comment]
@dhiller can we unhold?

**Review by brianmcarey — COMMENTED** [review]
/hold cancel

I think we can take this in. 

Thanks @acardace 

/lgtm

**Pull request merged**
