### PR TITLE
Bump bootstrap base image

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by fgimenez** [comment]
build running here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1461720182132051968

**Comment by rmohr** [comment]
> build running here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1461720182132051968

Hm, the pod seems have been unschedulable. Probably due to leaving the phx cluster behind but still having this selector

```
  nodeSelector:
    type: vm
```

**Comment by fgimenez** [comment]
> Hm, the pod seems have been unschedulable. Probably due to leaving the phx cluster behind but still having this selector

great catch! there are a few of them (also a couple of misplaced jobs), will be fixed with #1748

**Comment by fgimenez** [comment]
there was a weird error with f35, running the build here with f34 https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-bootstrap-image/1462738900375048192

**Comment by fgimenez** [comment]
was successful, job to test `quay.io/kubevirtci/bootstrap:v20211122-74f6742` running here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.21-operator/1462742627261616128

**Comment by fgimenez** [comment]
@rmohr all is looking good here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.21-operator/1462742627261616128 PTAL

**Comment by rmohr** [comment]
Awesome. :+1: 

/lgtm
/approve

**Pull request merged**
