### PR TITLE
Update to user-guide Dockerfile and spelling dictionary

### PR DESCRIPTION
**Pull request by mazzystr**
Update to user-guide Dockerfile to synchronize software versions, add plugin, update spelling dictionary
Update to spelling dictionary

### CODE REVIEW

**Comment by dhiller** [comment]
I've created #840 to aid you in automatically testing and updating new image versions.

**Comment by mazzystr** [comment]
> I've created #840 to aid you in automatically testing and updating new image versions.

Oh that's cool! Thank you for that!

We've had a mix of container and bare metal for several applications regarding development associated with the website and user-guide.  Do you think we should we should just transition to 100% containerization at this point?  Pinging @codificat

**Comment by mazzystr** [comment]
@dhiller This pull req is ready for merge

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
