### PR TITLE
prow: Update prow-deploy and bumper to use new location for prow images

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

Prow have started publishing to a new location[1] which has resulted in the autobump no longer working[2]

Change to using the new location for the prow images

[1] https://github.com/kubernetes/test-infra/commit/45e3aa72504c35c9b2243e2ecd87ed9c1125405f
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-project-infra-prow-bump/1824327883812769792#1:build-log.txt%3A75

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/cc @dhiller @xpivarc 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by brianmcarey** [comment]
/hold

As myself and @dhiller are away next week - this update can wait until we are back.

**Comment by brianmcarey** [comment]
/hold cancel

rehearsals failures are not related to change - i think this should be good for review now.

**Review by dhiller — APPROVED** [review]
Thank you @brianmcarey - although the image names look quite weird, let's give this a try :slightly_smiling_face: 

/approve

**Comment by brianmcarey** [comment]
/override  rehearsal-build-autoowners-image
/override rehearsal-build-fedora-coreos-kubevirt-image
/override rehearsal-build-kubevirt-kubevirt.github.io-image
/override rehearsal-build-kubevirt-user-guide-image 
/override rehearsal-pull-project-infra-ci-search-deploy-test

overriding unrelated rehearsals.

**Pull request merged**
