### PR TITLE
Disable quarantine lanes

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
With other words, they were added and enabled too fast.

**Comment by fgimenez** [comment]
Sure, the automatic execution is disabled until the queue is empty, the worker nodes have a lot of pressure. Once the queue is empty the quarantine lanes will be enabled again, we can trigger them manually meanwhile.

**Comment by fgimenez** [comment]
We also have a bare metal down since yesterday, which makes the pending job queue longer.

**Comment by EdDev** [comment]
OK, I think I get it.
Well, they do something: Show us the problems.
But we can just move them to a periodic run, which seems more appropriate.

**Review by enp0s3 — APPROVED** [review]
/approve

**Pull request merged**
