### PR TITLE
perf-report-creator: modify to scrape sig-scale jobs in density cluster

### PR DESCRIPTION
**Pull request by alaypatel07**
This is a follow up PR from #2741. With the change in regex, it is now also possible to scrape the sig-scale jobs in the density cluster.

The difference between the performance and density jobs is that the former has 3 different results, vmi, vm and vm with preference types, while the density jobs are specifically for vmis. 

This PR changes the code execution such that results will not be collected for vms in case of density jobs and handles other corner cases in weekly-report

cc @rthallisey

### CODE REVIEW

**Comment by alaypatel07** [comment]
I was able to try out the density 100 job scrape, here are the results:
```
$ perf-report-creator results --credentials-file=/Users/alayp/.gcp_credentials.json --output-dir trial/results --since 168h0m0s --performance-job-name periodic-kubevirt-performance-cluster-100-density-test
..
<output-snipped>
..
$ ls trial/results/periodic-kubevirt-performance-cluster-100-density-test   
1656157214471098368     1656519669500088320     1656882075384418304     1657244468283183104     1657606860963844096     1657969254487560192     1658331648036442112

$ perf-report-creator weekly-report --output-dir=trial/weekly/periodic-kubevirt-performance-cluster-100-density-test --results-dir=trial/results/periodic-kubevirt-performance-cluster-100-density-test --vmi-metrics-list=vmiCreationToRunningSecondsP95,LIST-virtualmachineinstances-count,LIST-pods-count,LIST-nodes-count,LIST-virtualmachineinstancemigrations-count,LIST-endpoints-count,GET-virtualmachineinstances-count,GET-pods-count,GET-nodes-count,GET-virtualmachineinstancemigrations-count,GET-endpoints-count,CREATE-virtualmachineinstances-count,CREATE-pods-count,CREATE-nodes-count,CREATE-virtualmachineinstancemigrations-count,CREATE-endpoints-count,PATCH-virtualmachineinstances-count,PATCH-pods-count,PATCH-nodes-count,PATCH-virtualmachineinstancemigrations-count,PATCH-endpoints-count,UPDATE-virtualmachineinstances-count,UPDATE-pods-count,UPDATE-nodes-count,UPDATE-virtualmachineinstancemigrations-count,UPDATE-endpoints-count --vm-metrics-list vmiCreationToRunningSecondsP95,LIST-virtualmachineinstances-count,LIST-pods-count,LIST-nodes-count,LIST-virtualmachineinstancemigrations-count,LIST-endpoints-count,GET-virtualmachineinstances-count,GET-pods-count,GET-nodes-count,GET-virtualmachineinstancemigrations-count,GET-endpoints-count,CREATE-virtualmachineinstances-count,CREATE-pods-count,CREATE-nodes-count,CREATE-virtualmachineinstancemigrations-count,CREATE-endpoints-count,PATCH-virtualmachineinstances-count,PATCH-pods-count,PATCH-nodes-count,PATCH-virtualmachineinstancemigrations-count,PATCH-endpoints-count,UPDATE-virtualmachineinstances-count,UPDATE-pods-count,UPDATE-nodes-count,UPDATE-virtualmachineinstancemigrations-count,UPDATE-endpoints-count
..
<output-snipped>
..
$ perf-report-creator weekly-graph --resource=vmi --weekly-reports-dir=/Users/alayp/nid/project-infra/robots/cmd/perf-report-creator/trial/weekly/periodic-kubevirt-performance-cluster-100-density-test --plotly-html=true --metrics-list=vmiCreationToRunningSecondsP95,LIST-virtualmachineinstances-count,LIST-pods-count,LIST-nodes-count,LIST-virtualmachineinstancemigrations-count,LIST-endpoints-count,GET-virtualmachineinstances-count,GET-pods-count,GET-nodes-count,GET-virtualmachineinstancemigrations-count,GET-endpoints-count,CREATE-virtualmachineinstances-count,CREATE-pods-count,CREATE-nodes-count,CREATE-virtualmachineinstancemigrations-count,CREATE-endpoints-count,PATCH-virtualmachineinstances-count,PATCH-pods-count,PATCH-nodes-count,PATCH-virtualmachineinstancemigrations-count,PATCH-endpoints-count,UPDATE-virtualmachineinstances-count,UPDATE-pods-count,UPDATE-nodes-count,UPDATE-virtualmachineinstancemigrations-count,UPDATE-endpoints-count
..
<output-snipped>
..
$ ls trial/weekly/periodic-kubevirt-performance-cluster-100-density-test/vmi 
CREATE-endpoints-count                          GET-pods-count                                  LIST-virtualmachineinstances-count              UPDATE-nodes-count
CREATE-nodes-count                              GET-virtualmachineinstancemigrations-count      PATCH-endpoints-count                           UPDATE-pods-count
CREATE-pods-count                               GET-virtualmachineinstances-count               PATCH-nodes-count                               UPDATE-virtualmachineinstancemigrations-count
CREATE-virtualmachineinstancemigrations-count   LIST-endpoints-count                            PATCH-pods-count                                UPDATE-virtualmachineinstances-count
CREATE-virtualmachineinstances-count            LIST-nodes-count                                PATCH-virtualmachineinstancemigrations-count    index.html
GET-endpoints-count                             LIST-pods-count                                 PATCH-virtualmachineinstances-count             vmiCreationToRunningSecondsP95
GET-nodes-count                                 LIST-virtualmachineinstancemigrations-count     UPDATE-endpoints-count

```

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
