### PR TITLE
Bump prow to v20200204-7e8cd997a

### PR DESCRIPTION
**Pull request by rmohr**
Bump to latest prow.

### CODE REVIEW

**Comment by dhiller** [comment]
What was the matter with the failing prow check? Was it just, that the check was old, like it was not the right one that should be applied by the PR?

**Comment by dhiller** [comment]
Otherwise 

/lgtm

**Comment by rmohr** [comment]
> What was the matter with the failing prow check? Was it just, that the check was old, like it was not the right one that should be applied by the PR?

The checkconfig job is not yet updated. It will pass after we merged this PR. Here my local check:

```
$ docker run --rm -v ${PWD}/:/prow  -it gcr.io/k8s-prow/checkconfig:v20200204-7e8cd997a  --config-path /prow/files/config.yaml --job-config-path /prow/files/jobs --plugin-config /prow/files/plugins.yaml --strict
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:325","func":"main.main","level":"info","msg":"checkconfig passes without any error!","time":"2020-02-06T09:11:34Z"}
```

**Comment by dhiller** [comment]
So then, fasten your seat belts :)

**Comment by dhiller** [comment]
And always wear a helmet :-D

**Pull request merged**
