### PR TITLE
WIP: try label

### PR DESCRIPTION
**Pull request by oshoval**

### CODE REVIEW

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3146/rehearsal-pull-kubevirt-e2e-k8s-1.26-sig-network/1739288374100889600

with FOCUS test_id, it works

**Comment by dhiller** [comment]
@dhiller's review-bot says:

:thumbsdown: This doesn't look like a simple prow job image bump.

<details>

_github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml_

~~~diff
           label:lgtm label:approved
           status:failure
           -label:needs-rebase
+          -label:needs-ok-to-test
           repo:kubevirt/kubevirt
           repo:kubevirt/kubevirtci
       - --token=/etc/github/oauth

~~~

~~~diff
         resources:
           requests:
             memory: "200Mi"
-- name: periodic-bump-crio-mirror-versions
-  interval: 24h
-  max_concurrency: 1
-  annotations:
-    testgrid-create-test-group: "false"
-  labels:
-    preset-github-credentials: "true"
-  decorate: true
-  decoration_config:
-    timeout: 1h
-    grace_period: 5m
-  extra_refs:
-  - org: kubevirt
-    repo: project-infra
-    base_ref: main
-    workdir: true
-  cluster: kubevirt-prow-control-plane
-  spec:
-    securityContext:
-      runAsUser: 0
-    containers:
-      - image: quay.io/kubevirtci/pr-creator:v20230103-9f4e101
-        command: ["/bin/sh"]
-        args:
-          - "-c"
-          - git-pr.sh -c "./hack/bump-crio-mirror-versions.sh" -p ./ -r project-infra -b crio-version-bump -T main
-        resources:
-          requests:
-            memory: "200Mi"
 - name: periodic-kubevirtci-cluster-unsupported-version-remover
   cron: "30 3 * * *"
   max_concurrency: 1

~~~

~~~diff
         command: [ "/bin/sh" , "-c" ]
         args:
           - |
-            git-pr.sh -c "bazel run //robots/cmd/kubevirt require presubmits -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --github-token-path= --dry-run=false && bazel run //robots/cmd/kubevirt remove always_run -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --github-token-path= --dry-run=false" -r project-infra -b require-kubevirt-presubmits -T main -s 'Enable e2e lanes for latest kubernetes version' -B $'Enable lanes for latest kubernetes version and disable lanes with unsupported version\n\n/cc @kubevirt/prow-job-taskforce'
-            
+            git-pr.sh -c "bazel run //robots/cmd/kubevirt require presubmits -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --github-token-path= --dry-run=false" -r project-infra -b require-kubevirt-presubmits -T main
         resources:
           requests:
             memory: "200Mi"

~~~

~~~diff
         requests:
           memory: "200Mi"
 
+- name: periodic-kubevirt-job-always-run-disabler
+  cron: "45 0 * * *"
+  max_concurrency: 1
+  annotations:
+    testgrid-create-test-group: "false"
+  labels:
+    preset-github-credentials: "true"
+  decorate: true
+  decoration_config:
+    timeout: 1h
+    grace_period: 5m
+  extra_refs:
+  - org: kubevirt
+    repo: project-infra
+    base_ref: main
+    workdir: true
+  cluster: kubevirt-prow-control-plane
+  spec:
+    securityContext:
+      runAsUser: 0
+    containers:
+    - image: quay.io/kubevirtci/pr-creator:v20230103-9f4e101
+      env:
+      command: [ "/bin/sh" , "-c" ]
+      args:
+      - |
+        git-pr.sh -c "bazel run //robots/cmd/kubevirt remove always_run -- --job-config-path-kubevirt-presubmits=$(pwd)/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml --github-token-path= --dry-run=false" -r project-infra -b disable-kubevirt-jobs -T main
+      resources:
+        requests:
+          memory: "200Mi"
+
 - name: periodic-project-infra-mirror-istioctl
   cron: "25 1 * * 1"
   decorate: true

~~~

</details>

:thumbsup: This looks like a simple prow autobump.

This PR does not satisfy at least one automated review criteria.

Holding this PR because:
* prow update should be merged at a point in time where it doesn't interfere with normal CI usage

/hold

**Note: botreview (kubevirt/project-infra#3100) is a Work In Progress!**

**Pull request closed without merging**
