### PR TITLE
cnao, Add e2e monitoring lane

### PR DESCRIPTION
**Pull request by RamLavi**
This PR adds a new monitoring lane that runs prometheus related tests.

### CODE REVIEW

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Comment by phoracek** [comment]
/hold

Feel free to cancel the hold when ready

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Comment by RamLavi** [comment]
/retest

@fgimenez is this a known issue, or am I missing something?

**Comment by brianmcarey** [comment]
@RamLavi pull-project-infra-check-testgrid-config is failing constantly due to an issue with a missing dependency - the job is currently set to optional so it is not required for merge. I think this change should be good to go in once the hold is removed.

**Pull request merged**
