### PR TITLE
presubmit e2e-arm64: use kind-1.28 to do the test

### PR DESCRIPTION
**Pull request by zhlhahaha**

### CODE REVIEW

**Comment by zhlhahaha** [comment]
/hold
until https://github.com/kubevirt/kubevirtci/pull/1098 get merged and be dump to kubevirt
cc: @oshoval @brianmcarey @dhiller @xpivarc

**Review by oshoval — APPROVED** [review]
Thanks

**Review by brianmcarey — COMMENTED** [review]
thanks @zhlhahaha  - looks good. 

Can you update the periodic arm lane to use the same TARGET? 
https://github.com/kubevirt/project-infra/blob/0dbfdd056673020ed578d3e59ea82b7a840ea20c/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L703

**Review by brianmcarey — APPROVED** [review]
/approve

**Comment by zhlhahaha** [comment]
/?

**Comment by zhlhahaha** [comment]
The tests have passed. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3088/rehearsal-pull-kubevirt-e2e-arm64/1728953184459689984
/unhold

**Pull request merged**
