### PR TITLE
Make CDI jobs required on the CDI repo

### PR DESCRIPTION
**Pull request by rmohr**
Make CDI jobs required.

### CODE REVIEW

**Comment by rmohr** [comment]
/cc @awels 

you can approve it once you are setisfied with the test runs in CDI.

**Comment by rmohr** [comment]
/hold

needs https://github.com/kubevirt/containerized-data-importer/pull/995 merged first.

**Comment by awels** [comment]
@rmohr any chance we can get coveralls enabled in https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/config.yaml for cdi as well? it disappeared some time ago for us.

**Comment by rmohr** [comment]
> @rmohr any chance we can get coveralls enabled in https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/config.yaml for cdi as well? it disappeared some time ago for us.

Done.

**Pull request merged**
