### PR TITLE
Fix: CDI control plane has no access to Goveralls token

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**What this PR does / why we need it**:
PRs #3350 and #3369 have laid the ground work to enable Coveralls reports for the Containerized Data Importer repository. This has been a bit of a trial and error, and the error now is that the secret coveralls token is not available to the cluster running the job:

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3197/pull-cdi-goveralls/1783542761547370496

This PR fixes this.

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
Is there any way of running `pull-cdi-goveralls` before merging to avoid so much trial-and-error, or do we just have to keep trying?

**Comment by dhiller** [comment]
@EduardGomezEscandell I think there's no way for you to run a rehearsal. I'll take a look.

**Comment by dhiller** [comment]
> @EduardGomezEscandell I think there's no way for you to run a rehearsal. I'll take a look.

@EduardGomezEscandell I see now that this is a change in how the secrets are deployed to our clusters. So this change is not testable by a rehearsal anyway.

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
