### PR TITLE
Rehearse: Implement periodics support + small refactor

### PR DESCRIPTION
**Pull request by xpivarc**
I recommend reviewing commit by commit.
/cc @dhiller @brianmcarey

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
@xpivarc thank you for refactoring the test code! :tada: 

I figure that you are still working on this, since I saw some tests that were changed to pending.

**Comment by xpivarc** [comment]
> @xpivarc thank you for refactoring the test code! tada
> 
> I figure that you are still working on this, since I saw some tests that were changed to pending.

I left them intentionally open, and up to discussion as I am not sure I see value there.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

thanks for this - it looks great. Breaking up the refactor into commits was a great help!

**Comment by xpivarc** [comment]
New: last 3 commits.
Removed `rehearsal.allowed`.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
