### PR TITLE
kubevirt,presubmit: Bump single stack ipv6 lane to 1.30

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by oshoval** [comment]
/hold

injected rehearsal workaround unset PULL_BASE_SHA
that need to be removed after rehearsing

**Comment by oshoval** [comment]
/hold cancel

removed injection, lets test rehearsal when the fix is merged to kubevirt

**Comment by oshoval** [comment]
/hold

cherry-picked https://github.com/kubevirt/kubevirt/pull/11829
lets try it with rehearse

**Comment by oshoval** [comment]
this is weird
while it ran i could see the log
but when it done i cant see the log and know why it failed
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3388/rehearsal-pull-kubevirt-e2e-k8s-1.30-ipv6-sig-network/1786029488383987712

also artifacts doesnt have the log from a glance unless i missed it

@brianmcarey are you familiar with this problem ?

**Comment by oshoval** [comment]
> > this is weird while it ran i could see the log but when it done i cant see the log and know why it failed https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/3388/rehearsal-pull-kubevirt-e2e-k8s-1.30-ipv6-sig-network/1786029488383987712
> > also artifacts doesnt have the log from a glance unless i missed it
> > @brianmcarey are you familiar with this problem ? note that it happens on more PRs, mentioned you on one
> 
> Yes there is an issue with the vgpu nodes crashing and rebooting. This can lead to jobs with the empty logs as you mentioned. I have them cordoned for now.

thanks
nice find

**Review by brianmcarey — COMMENTED** [review]
Looks good @oshoval  - can you just remove the test patch and this should be good to go.

**Comment by oshoval** [comment]
Done

/hold cancel

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
