### PR TITLE
Use docker-proxy in CDI jobs

### PR DESCRIPTION
**Pull request by fgimenez**
/cc @awels @maya-r @dhiller 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/lgtm
/approve
/hold

Just holding for other people to look at the changes. Remove whenever you want :slightly_smiling_face:

**Comment by fgimenez** [comment]
rehearse jobs are failing to fetch the main branch:
```
$ git fetch https://github.com/kubevirt/containerized-data-importer.git master
fatal: Couldn't find remote ref master
```
I've triggered manually one of the presubmits with the changes to use the docker proxy and the branch from https://github.com/kubevirt/containerized-data-importer/pull/1667 and it went fine https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1667/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1362449225094270976

**Comment by fgimenez** [comment]
/unhold

Going ahead with this one, will keep an eye on the builds @awels @maya-r give me a shout if something is not working as expected.

**Comment by fgimenez** [comment]
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-ceph rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-ember-lvm rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-hpp rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-hpp rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-hpp-destructive rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-nfs rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-upg

**Comment by fgimenez** [comment]
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-ceph 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-ember-lvm 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.17-hpp 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-hpp 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-hpp-destructive 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-nfs 
/override rehearsal-pull-containerized-data-importer-e2e-k8s-1.18-upg

**Pull request merged**
