### PR TITLE
Switch CDI postsubmit jobs to use podman

### PR DESCRIPTION
**Pull request by maya-r**
It works fine with buildah/podman

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by akalenyu** [comment]
Is there a way to rehearse these? I think we had some sort of issue with these image pushing jobs and podman

**Comment by maya-r** [comment]
If not, one of the jobs runs on the latest commit, so we should be able to see a failure pretty much right away after merging

**Comment by brianmcarey** [comment]
> Is there a way to rehearse these? I think we had some sort of issue with these image pushing jobs and podman

We don't have a way of rehearsing postsubmits currently as we don't want rehearsals actually publishing any artifacts etc.

**Review by akalenyu — APPROVED** [review]
lgtm

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
