### PR TITLE
kubevirt-presubmits: Enable Istio tests to run with 1.26 CentOS Stream 9

### PR DESCRIPTION
**Pull request by EdDev**
Istio should run fine now with CentOS Stream 9.

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
Should this be changed on the multus v4 lane too? `pull-kubevirt-e2e-k8s-1.26-sig-network-multus-v4`

**Comment by EdDev** [comment]
> Should this be changed on the multus v4 lane too? `pull-kubevirt-e2e-k8s-1.26-sig-network-multus-v4`

Yes, missed it!
Thanks.

**Comment by EdDev** [comment]
change: Covered `pull-kubevirt-e2e-k8s-1.26-sig-network-multus-v4` as well.

**Comment by AlonaKaplan** [comment]
Can you please add a link the the istio issue/release fixing the problem (I think it was them using iptables, right?)?

**Comment by EdDev** [comment]
> Can you please add a link the the istio issue/release fixing the problem (I think it was them using iptables, right?)?

Everything is recorded in the issue that tracked it: https://github.com/kubevirt/kubevirt/issues/9158
It includes ref to Istio issue as well.

**Pull request merged**
