### PR TITLE
Let the reconciler use our github request cache

### PR DESCRIPTION
**Pull request by rmohr**
Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

still checking.

**Comment by rmohr** [comment]
/hold cancel

Seems to work.

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Comment by dhiller** [comment]
Has this already been rolled out?

**Comment by rmohr** [comment]
it was in the past. We can merge the PR. status reconciler is disabled right now.

**Pull request merged**
