### PR TITLE
code lint: Make linter lane not optional

### PR DESCRIPTION
**Pull request by rhrazdil**
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

### CODE REVIEW

**Comment by rhrazdil** [comment]
It seems that we can consider the linter job to be stable:
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-code-lint
Any reason to not make it mandatory?

/hold cancel

**Comment by xpivarc** [comment]
> /cc @xpivarc

I am not sure if the discussion in https://groups.google.com/d/msgid/kubevirt-dev/CA%2BPVUaSz5kjN-NS1muu0PXznbtPFjch6C%2BeYjLXfWF1Z16PXgw%40mail.gmail.com?utm_medium=email&utm_source=footer has settled.

**Pull request closed without merging**
