### PR TITLE
Request adding alromeros to org members

### PR DESCRIPTION
**Pull request by alromeros**
# GitHub Username
@alromeros

## Requirements

- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
- [x] I am actively contributing to KubeVirt<br>
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
- [x] I have publicly introduced myself to the community through one of the community communication channels<br>

## Sponsors
- @aglitke 
- @awels 

## List of contributions to the KubeVirt project

- https://github.com/kubevirt/containerized-data-importer/pull/2222

### CODE REVIEW

**Comment by rmohr** [comment]
@alromeros thanks for the PR! We have a join process outlined in https://github.com/kubevirt/community/blob/main/membership_policy.md. Would you mind going through it? Let us know if you have any questions.

**Comment by aglitke** [comment]
Please add me as a sponsor

**Comment by rmohr** [comment]
> The document mentions that `Sponsors must be reviewers or approvers in the KubeVirt OWNERS file`, but I don't really know which **OWNERS** file should I take into account: [This](https://github.com/kubevirt/project-infra/blob/main/OWNERS), [this](https://github.com/kubevirt/kubevirt/blob/main/OWNERS_ALIASES), or [this](https://github.com/kubevirt/community/blob/main/OWNERS) one?

You are right, we are not clear about it. In fact any of these (also kubevirt/contaierized-data-importer would be perfectly fine). Basically you need tow people which are sponsoring you which have some trust by being in one of the OWNERS files in one of the kubevirt projects.

**Comment by alromeros** [comment]
> You are right, we are not clear about it. In fact any of these (also kubevirt/contaierized-data-importer would be perfectly fine). Basically you need tow people which are sponsoring you which have some trust by being in one of the OWNERS files in one of the kubevirt projects.

All right, that makes sense. Thanks!

**Pull request merged**
