### PR TITLE
Deploy grafana instance to control plane cluster

### PR DESCRIPTION
**Pull request by brianmcarey**
Includes integration with the built in cluster-monitoring prometheus instance and a basic set of dashboards

/cc @dhiller @xpivarc

### CODE REVIEW

**Comment by brianmcarey** [comment]
/hold 

requires the correct token be added to secrets

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
> /hold
> 
> requires the correct token be added to secrets

I think that PR should be merged.

**Pull request merged**
