### PR TITLE
Add kuberhealthy deployment

### PR DESCRIPTION
**Pull request by fgimenez**
Test and deployment code for a basic [Kuberhealthy](https://github.com/Comcast/kuberhealthy) installation. Includes 3 preconfigured synthetic checks for damonset, deployment and dns status. Includes ingress for accessing the status page at https://status.ci.kubevirt.io

I've taken the opportunity to refactor the HTTP service checks in the `github/ci/services` deployments e2e tests.

/cc @rmohr @dhiller 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
/lgtm
/approve
/hold

One thing: maybe we can extract the secret extraction shell part from the jobs (now there are several that are using this IIRC) into a script and put it into `hack`? Could maybe something for another PR, not sure....

**Comment by fgimenez** [comment]
> One thing: maybe we can extract the secret extraction shell part from the jobs (now there are several that are using this IIRC) into a script and put it into `hack`? Could maybe something for another PR, not sure....

makes total sense :+1:  will work on that in a follow-up

**Pull request merged**
