### PR TITLE
Revert disabling rook-ceph

### PR DESCRIPTION
**Pull request by rmohr**
Re-enavbling ceph due to mailing list feedback.

### CODE REVIEW

**Comment by rmohr** [comment]
/approve
/hold

@awels feel free to lgtm and cancel the hold whenever you see fit.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Review by davidvossel — COMMENTED** [review]
/hold

unhold when you all are ready

**Comment by EdDev** [comment]
But this is a 1.17 lane, we know it is problematic and will fail frequently. Has something changed?
Was this job less prone to failures?

**Comment by awels** [comment]
On Tue, Mar 9, 2021 at 8:29 AM Edward Haas <notifications@github.com> wrote:

> But this is a 1.17 lane, we know it is problematic and will fail
> frequently. Has something changed?
>
Was this job less prone to failures?
>

Its the 1.17 rook-ceph lane, this is a special lane that runs a limited
number of tests, in particular related to storage operations available in
KubeVirt like snapshot and block device operations. It is actually very
stable except for one test we have identified.

**Comment by awels** [comment]
If someone can ack https://github.com/kubevirt/kubevirt/pull/5178 and guide it in, then we can re-enable to rook-ceph lane. I have had 3 continuous runs without failures with the fix applied.

**Comment by awels** [comment]
/hold cancel
Fix was merged, lane should be relatively stable at this point.

**Pull request merged**
