### PR TITLE
Update capk and cloud provider presubmits to use podman

### PR DESCRIPTION
**Pull request by brianmcarey**
Includes removal of the prow config for a capk fork that is no longer maintained. 

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Comment by brianmcarey** [comment]
Rehearsal failures unrelated to podman change. 
-  rehearsal-pull-cluster-api-provider-kubevirt-e2e: missing 1.21 kubevirtci provider
- rehearsal-pull-cluster-api-provider-kubevirt-conformance-e2e : conformance make target missing. 

/cc @qinqon

**Comment by brianmcarey** [comment]
I believe those rehearsal failures come from this temporary fork - https://github.com/kubevirt/cluster-api-provider-kubevirt#this-is-a-temporary-fork-of-httpsgithubcomkubernetes-sigscluster-api-provider-kubevirt

cc @rmohr  - are we still maintaining this fork or are these rehearsal prowjob failures ok to ignore?

**Comment by rmohr** [comment]
> I believe those rehearsal failures come from this temporary fork - https://github.com/kubevirt/cluster-api-provider-kubevirt#this-is-a-temporary-fork-of-httpsgithubcomkubernetes-sigscluster-api-provider-kubevirt
> 
> cc @rmohr - are we still maintaining this fork or are these rehearsal prowjob failures ok to ignore?

Ah yes, it is not used anymore. We can delete all configs for it.

**Pull request merged**
