### PR TITLE
Make NonRoot network lane required

### PR DESCRIPTION
**Pull request by xpivarc**

### CODE REVIEW

**Comment by xpivarc** [comment]
/hold 
I found a failure in the storage lane.

**Review by dhiller — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
I just noticed that you don't make them required but just that they will run always and still stay optional? Maybe you need to adjust the PR description then?

**Comment by xpivarc** [comment]
> I just noticed that you don't make them required but just that they will run always and still stay optional? Maybe you need to adjust the PR description then?

Thanks for catching this. It was unintentional. I changed this PR so it's only changing network lane. I am going to run one test on main to confirm this is safe to merge.

**Comment by xpivarc** [comment]
/hold cancel
@brianmcarey Could you re-apply lgtm? :)

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
