### PR TITLE
kubevirt: Add cnao k8s 1.17 lane.

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
/lgtm
/hold

Holding so we can test it against kubevirt

**Comment by qinqon** [comment]
@phoracek at the end I am just adding a new lane instead of replace, so we can merge this and when job is ok after few runs we set this at mandatory and remove the old one.

**Comment by phoracek** [comment]
Ok, then feel free to cancel the hold

**Pull request merged**
