### PR TITLE
kubesecondarydns, presubmits: Add build and unit-tests for s390x

### PR DESCRIPTION
**Pull request by jschintag**
**What this PR does / why we need it**:
Add testing for building and unit-tests on s390x to kubesecondarydns
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jschintag** [comment]
Should be fixed, for some reason it wanted to use CGO, despite not needing it, and failed to find the gcc binary.

**Comment by jschintag** [comment]
Yes i can add it to the makefile as well.

**Comment by oshoval** [comment]
> Yes i can add it to the makefile as well.

better please, lets add it and then remove it from here ?

**Comment by jschintag** [comment]
Done in https://github.com/kubevirt/kubesecondarydns/pull/77

**Review by brianmcarey — COMMENTED** [review]
/approve

Looks good to me.

**Comment by oshoval** [comment]
@ashokpariya0
might good to consider please doing the same for CNAO ? 
maybe even not always run but optional

**Comment by ashokpariya0** [comment]
> @ashokpariya0 might good to consider please doing the same for CNAO ? maybe even not always run but optional
Okay, Noted.

**Pull request merged**
