### PR TITLE
Enable dco plugin for kubevirt and kubevirtci

### PR DESCRIPTION
**Pull request by rmohr**

### CODE REVIEW

**Comment by rmohr** [comment]
@dhiller an alternative to the external DCO check.

**Comment by dhiller** [comment]
^^ @rmohr

**Comment by rmohr** [comment]
@dhiller You can enable it for the whole org by adding it to the plugins which are enabled for the whole org.

I would like to try it out first, I have never seen it in action.

**Comment by dhiller** [comment]
> I would like to try it out first, I have never seen it in action.

@rmohr OK, then let's try with your PR and see how it goes.

**Pull request merged**
