### PR TITLE
cnao: Use podman on presubmit jobs

### PR DESCRIPTION
**Pull request by oshoval**
Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
/rehearse pull-e2e-cluster-network-addons-operator-lifecycle-k8s

**Comment by oshoval** [comment]
/rehearse pull-e2e-cluster-network-addons-operator-lifecycle-k8s

**Comment by oshoval** [comment]
First time I see this error
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2125/rehearsal-pull-e2e-cluster-network-addons-operator-macvtap-cni-functests/1532263466876801024#1:build-log.txt%3A581
`Error: error creating build container: initializing source docker://quay.io/centos/centos:stream9: can't talk to a V1 container registry`

**Comment by oshoval** [comment]
/rehearse

only error so far 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2125/rehearsal-pull-e2e-cluster-network-addons-operator-workflow-k8s/1534095563631366144

**Comment by oshoval** [comment]
Hi @brianmcarey 
it seems rehearse doesnt work ?

Also can you please see if all the podman changes are correct ?
updated to the new official image + the pinc label

**Comment by brianmcarey** [comment]
> Hi @brianmcarey it seems rehearse doesnt work ?

Not sure why that is not working
> 
> Also can you please see if all the podman changes are correct ? updated to the new official image + the pinc label

the changes look good - you can just remove the added volumes and env variables as these should be added by the preset now.

**Comment by oshoval** [comment]
> > Hi @brianmcarey it seems rehearse doesnt work ?
> 
> Not sure why that is not working
> 
> > Also can you please see if all the podman changes are correct ? updated to the new official image + the pinc label
> 
> the changes look good - you can just remove the added volumes and env variables as these should be added by the preset now.

Thanks
you mean to remove all of those ?
https://github.com/kubevirt/project-infra/pull/2125/files#diff-d8e5bb0694ad46b80640b83b329dbdbebdebfe6a454f28e6b1c6d1e639f44980R31-R48
So just to keep the label + image?

**Comment by brianmcarey** [comment]
Yes exactly - and make sure you are rebased on the latest. The preset should bring in that extra config for you.

**Comment by oshoval** [comment]
Updated thanks, we just need rehearse

**Comment by oshoval** [comment]
ah nice rehearse works now

**Review by RamLavi — APPROVED** [review]
/lgtm

**Review by phoracek — COMMENTED** [review]
/approve

**Pull request merged**
