### PR TITLE
requesting community membership for kubevirt org

### PR DESCRIPTION
**Pull request by xphyr**
## GITHUB UserName
@xphyr

### Requirements
------
[x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)
[x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
[x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)
[x] I am actively contributing to KubeVirt
[x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
[x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application
[x] I have publicly introduced myself to the community through one of the community communication channels

### Sponsors
------
@vladikr 
@dhiller

### List of contributions to the KubeVirt project
-----
PRs reviewed and/or authored
[List of kubevirt PRs by @xphyr](https://github.com/pulls?q=is%3Apr+author%3Axphyr+kubevirt+)

### Issues responded to
-----
[#4207 Support for built-in vnc client on Mac](https://github.com/kubevirt/kubevirt/issues/4207)
[#4925 permittedHostDevices requires device ID to be in capital letters ](https://github.com/kubevirt/kubevirt/issues/4925)

Signed-off-by: Mark DeNeve <markd@xphyr.net>

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve
/hold

**Comment by mazzystr** [comment]
@davidvossel @fabiand @dhiller Why are we on hold here?  Is there something missing?

**Comment by dhiller** [comment]
Sorry, I was thinking that another review was required here. But as Vladik is a sponsor we should be good.

/unhold

**Review by dhiller — APPROVED** [review]

**Pull request merged**
