### PR TITLE
Persist merge-queue dashboard

### PR DESCRIPTION
**Pull request by fgimenez**
Shows historical information about https://github.com/fgimenez/ci-health/, looks like https://grafana.ci.kubevirt.io/d/WZU1-LPGz/merge-queue?orgId=1

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
Looks great :) One thing I remember is the unit in the upper diagram, maybe it would be more clear to change the headline to "average days to merge" or so?

**Comment by fgimenez** [comment]
Good point! fixed

**Review by dhiller — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
