### PR TITLE
Add openssh-server to bootstrap image

### PR DESCRIPTION
**Pull request by fossedihelm**
`scp` command requires running openssh-server to works with sftp
We cannot use `systemctl start sshd` since `System has not been booted with systemd as init system`.
For this, we need to generate the keys and start the process manually.

required by: https://github.com/kubevirt/kubevirt/pull/8410

/cc @brianmcarey

### CODE REVIEW

**Comment by akalenyu** [comment]
just making sure, we don't want this in the legacy bootstrap right?
https://github.com/kubevirt/project-infra/blob/cb00eb93d2cadd4b016822807eafb2065a759533/images/bootstrap-legacy/Dockerfile#L17

**Comment by fossedihelm** [comment]
@brianmcarey @akalenyu Covered `bootstrap-legacy`

**Comment by akalenyu** [comment]
/lgtm

Thanks:pray:

**Comment by fossedihelm** [comment]
@akalenyu Pushed changes since there will be issue running `systemctl`
```
[root@565c36c623e8 workspace]# systemctl start sshd
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by brianmcarey** [comment]
/hold

This may be related to the cirros image used to spin up the test vm - putting on hold for now.

**Comment by fossedihelm** [comment]
> /hold
> 
> This may be related to the cirros image used to spin up the test vm - putting on hold for now.

Confirmed! The`openssh-server` error is related to the cirros image.
Close this.

/close

**Pull request closed without merging**
