### PR TITLE
Add document on AMD SEV testing cluster

### PR DESCRIPTION
**Pull request by brianmcarey**
Short document on the newly added AMD SEV Cluster that will be used for testing KubeVirt and SEV.

/cc @dhiller @xpivarc @vasiliy-ul 

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Review by vasiliy-ul — APPROVED** [review]
Looks good!

**Comment by larrydewey** [comment]
> /cc @larrydewey I'm adding a quick document on the AMD node for testing KubeVirt with SEV, any other details worth adding?

Nope, this looks pretty good. It might be worth noting that this is a second generation (Rome) AMD EPYC processor, so it does support both SEV and SEV-ES. Other than that, this is well done! @ryansavino or @UnmeshDeodhar, can you think of anything to add here?

**Review by larrydewey — APPROVED** [review]
LGTM!

**Comment by vasiliy-ul** [comment]
> it does support both SEV and SEV-ES

There is a PR https://github.com/kubevirt/kubevirt/pull/7742 which enables ES in KubeVirt and currently the e2e test is skipped there because the node is not properly labeled. The label is added after querying the hypervisor capabilities. It seems that `virsh nodesevinfo` returns `max-es-guests = 0` on the node:

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9293/pull-kubevirt-e2e-k8s-1.26-sev/1628313823817502720

```
      pdh               :  <...>
      cert-chain        :  <...>
      cpu0-id           : <...>
      cbitpos           : 47
      reduced-phys-bits : 1
      max-guests        : 509
      max-es-guests     : 0
```

AFAIK, enabling ES also requires changing the BIOS settings and allocate a number of ASIDs for SEV-ES. Can we somehow check the BIOS on that machine and adjust the settings?

/cc @Fuzzy-Math

**Comment by vasiliy-ul** [comment]
CC: @Fuzzy-Math

**Review by vasiliy-ul — APPROVED** [review]

**Comment by vasiliy-ul** [comment]
> Can we somehow check the BIOS on that machine and adjust the settings?

This has been addressed: `max-es-guests     : 14`

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
