### PR TITLE
Add jschintag to kubevirt members

### PR DESCRIPTION
**Pull request by jschintag**
# GitHub Username
@jschintag

## Requirements

- [x] I have reviewed the community code of conduct (https://github.com/kubevirt/kubevirt/blob/master/CODE_OF_CONDUCT.md)<br>
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)<br>
- [x] I have subscribed to the kubevirt-dev e-mail list (https://groups.google.com/forum/#!forum/kubevirt-dev)<br>
- [x] I am actively contributing to KubeVirt<br>
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines<br>
- [x] I have spoken to my sponsors ahead of this application and they have agreed to sponsor my application<br>
- [x] I have publicly introduced myself to the community through one of the community communication channels<br>

(https://github.com/kubevirt/community#socializing)

## Sponsors

* @brianmcarey 
* @dhiller 

## List of contributions to the KubeVirt project

* PRs reviewed and/or authored
- https://github.com/kubevirt/kubevirt/pull/10490
- https://github.com/kubevirt/kubevirt/pull/10836
- https://github.com/kubevirt/kubevirt/pull/11047
- https://github.com/kubevirt/kubevirt/pull/11493
- https://github.com/kubevirt/kubevirt/pull/11602
- https://github.com/kubevirt/kubevirt/pull/11097
* Issues responded to
- https://github.com/kubevirt/kubevirt/issues/8765
-
-

## Reason for joining

I am currently working on enabling kubevirt to run on the s390x architecture. For that reason i would like to join the kubevirt org to be able to better maintain the s390x support, as well as general multi-arch support.

> [!IMPORTANT]
> After this pull request has been merged, an invitation to the KubeVirt GitHub organization will be automatically sent to the new member. The new member needs to accept the invitation to receive member status.

### CODE REVIEW

**Comment by dhiller** [comment]
/cc

Would happily sponsor you @jschintag 

FYI @fabiand

**Review by dhiller — COMMENTED** [review]
/approve

/hold for some others to chime in

**Comment by jschintag** [comment]
@dhiller Thank you for sponsoring me, i have added you as a sponsor. I hope you have (had when you read this) a nice vacation.

**Comment by victortoso** [comment]
fwiw +1

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by dhiller** [comment]
/unhold

@jschintag welcome to the KubeVirt community! :tada:

**Pull request merged**
