### PR TITLE
WIP, test 6488

### PR DESCRIPTION
**Pull request by oshoval**
Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
1/1 pass

/test rehearsal-pull-kubevirt-e2e-kind-1.19-sriov

**Comment by oshoval** [comment]
2/2 pass
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1635/rehearsal-pull-kubevirt-e2e-kind-1.19-sriov/1443574307677540352

/rehearse

**Comment by oshoval** [comment]
3/3 pass
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1635/rehearsal-pull-kubevirt-e2e-kind-1.19-sriov/1443585875853185024

/rehearse

**Comment by oshoval** [comment]
4/4 passed
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1635/rehearsal-pull-kubevirt-e2e-kind-1.19-sriov/1443591883103145984

/rehearse

**Comment by oshoval** [comment]
5/5 pass
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1635/rehearsal-pull-kubevirt-e2e-kind-1.19-sriov/1443599330828095488

/rehearse

**Comment by oshoval** [comment]
6/6 passed

trying after the new PR update

/rehearse

**Comment by oshoval** [comment]
couldnt run on the node for 2 hours, retrying

/rehearse

**Comment by oshoval** [comment]
@fgimenez Hi, can we check please why it doesn't schedule the job for hours,
even that last week it was working ? (the node was part of the cluster, but just without the official labels as we spoke)

Thanks

**Comment by fgimenez** [comment]
> Hi, can we check please why it doesn't schedule the job for hours,
> even that last week it was working ? (the node was part of the cluster, but just without the official labels as we spoke)

yes, the node was reverted to its original labels and no node was machine the requirements in this PR, sorry about that. Let me know if you need the test labels back.

**Comment by oshoval** [comment]
Thanks Federico
lets try one time to see if i catch that node by chance, else i might need to readd the label

/rehearse

**Comment by oshoval** [comment]
@fgimenez 
I am closing this PR, the previous version of the PR passed 6/6 , and the new one is just cosmetics
no need to do anything but to approve https://github.com/kubevirt/kubevirt/pull/6488 
just note there will be flakes until this PR is approved 
let me know if you think otherwise please

**Pull request closed without merging**
